"""Regenerated Mark I operator tables (N02, issue #16).

The pinned reference engine is Mark I (R01: DEXED_ENGINE_MARKI). Its two
per-sample operator tables are computed at engine init from float formulas in
the pinned GPL tree (semantic specification only, never copied):

  sinLogTable[i] = round(-1024 * log2(x1)),
      x1 = float32(sin(((0.5+i)/1024) * pi/2))     (EngineMkI.cpp:83-86)
  sinExpTable[i] = round(x1),
      x1 = float32((pow(2, float(i)/1024) - 1) * 4096)  (EngineMkI.cpp:88-92)

The 1025-entry phase-increment LUT (Freqlut) comes from
`freqlut.cc:35-42`:

  y = 2^44 / sample_rate; inc = 2^(1/1024)
  lut[i] = int32(floor(y + 0.5)); y *= inc   for i in 0..1024

This module REGENERATES those bytes with our own generator (the
gen_tables.py regenerate-and-hash discipline; NUM-001: copy no bytes) and
pins them by SHA-256 in reference/tables/manifest.json. The operation order
above is mirrored exactly: double-precision sin/log2/pow with a single
float32 narrowing at x1 (struct round-trip), then C `round()`
(half-away-from-zero; the table domains are nonnegative, so floor(v+0.5)).

Determinism argument (DECISIONS-NUMERIC-v1 section 5, measured at N02):
- the quantity -1024*log2(x1) stays >= 1.8e-4 away from every half-integer
  rounding boundary (sinExpTable: >= 3.7e-5, its own margin), while any
  conforming libm agrees to ~1e-12 relative in double, so the rounded
  16-bit entries are platform-independent;
- measured: the pinned toolchain (Apple clang 21.0.0, this host) produces
  byte-identical tables for the float-returning and double-returning
  overload variants of the C++ table loops, and our Python regeneration
  hashes to
    sinlog  990c19e90732efe712a19ba4272f97c7c9d884ac0e4e19450a1067165d8aa8a8
    sinexp  e515a71ae736d92dcb3fd36973dea486c96d1521f1a0bab1f917be2c4ec07794
  which equal the provisional_records in spec/numeric-profile-v1.json.
- Freqlut accumulates 1024 doublings in double: NOT claimed byte-stable
  across libms (NUM-003). The frozen model pins its own generated bytes and
  declares the <= 1 phase-increment-LSB budget; the model-vs-reference
  divergence is counted by the N02 reference probe.

Stdlib only.
"""

from __future__ import annotations

import hashlib
import json
import math
import struct
from dataclasses import dataclass
from pathlib import Path

SINLOG_ENTRIES = 1024
SINLOG_BITS = 16
SINEXP_ENTRIES = 1024
SINEXP_BITS = 16
FREQLUT_ENTRIES = 1025
FREQLUT_BITS = 32

FREQLUT_MAX_LOGFREQ_INT = 20
FREQLUT_LG_N_SAMPLES = 10
FREQLUT_N_SAMPLES = 1 << FREQLUT_LG_N_SAMPLES
FREQLUT_SAMPLE_SHIFT = 24 - FREQLUT_LG_N_SAMPLES

A4_BASE_LOGFREQ = 50857777

MANIFEST_NAME = "manifest.json"


class TableDrift(Exception):
    """A pinned table does not match its manifest SHA-256."""


def _f32(x: float) -> float:
    """Narrow to IEEE-754 binary32 and widen back (the C `float` step)."""
    return struct.unpack("<f", struct.pack("<f", x))[0]


def _round_half_away(v: float) -> int:
    """C round(): half-away-from-zero. Both table domains are >= 0."""
    if v >= 0:
        return math.floor(v + 0.5)
    return math.ceil(v - 0.5)


def sin_log_table() -> tuple[int, ...]:
    """sinLogTable per EngineMkI.cpp:81-86 (operation order mirrored)."""
    out = []
    for i in range(SINLOG_ENTRIES):
        x1 = _f32(math.sin(((0.5 + i) / 1024.0) * math.pi / 2.0))
        out.append(_round_half_away(-1024.0 * math.log2(x1)))
    return tuple(out)


def sin_exp_table() -> tuple[int, ...]:
    """sinExpTable per EngineMkI.cpp:88-92 (operation order mirrored)."""
    out = []
    for i in range(SINEXP_ENTRIES):
        # pow(2, float(i)/1024): int + float -> C++ <cmath> promotes to the
        # double overload ([cmath.syn] additional-overload rule); the float32
        # quotient i/1024 is exact (i <= 1023 = 10 significand bits).
        x1 = _f32((2.0 ** (i / 1024.0) - 1.0) * 4096.0)
        out.append(_round_half_away(x1))
    return tuple(out)


def freqlut_table(sample_rate: float = 48000.0) -> tuple[int, ...]:
    """1025-entry int32 phase-increment LUT per freqlut.cc:35-42."""
    y = (1 << (24 + FREQLUT_MAX_LOGFREQ_INT)) / float(sample_rate)
    inc = 2.0 ** (1.0 / FREQLUT_N_SAMPLES)
    out = []
    for _ in range(FREQLUT_ENTRIES):
        out.append(math.floor(y + 0.5))
        y *= inc
    return tuple(out)


@dataclass(frozen=True)
class TableArtifact:
    name: str
    values: tuple[int, ...]
    bits: int
    signed: bool
    formula_citation: str
    formula: str

    @property
    def entries(self) -> int:
        return len(self.values)

    @property
    def fmt(self) -> str:
        return "<%d%s" % (len(self.values), "h" if not self.signed else "i")

    @property
    def data(self) -> bytes:
        return struct.pack(self.fmt, *self.values)

    @property
    def sha256(self) -> str:
        return hashlib.sha256(self.data).hexdigest()

    def hex_text(self) -> str:
        mask = (1 << self.bits) - 1
        width = self.bits // 4
        return "".join("%0*x\n" % (width, v & mask) for v in self.values)


def generate_all(sample_rate: float = 48000.0) -> dict[str, TableArtifact]:
    """Generate every N02 table artifact (pure, deterministic)."""
    return {
        "sinlog_table": TableArtifact(
            name="sinlog_table",
            values=sin_log_table(),
            bits=SINLOG_BITS,
            signed=False,
            formula_citation="EngineMkI.cpp:83-86 (dexed b6cf2e9)",
            formula="round(-1024 * log2(float32(sin(((0.5+i)/1024) * pi/2))))",
        ),
        "sinexp_table": TableArtifact(
            name="sinexp_table",
            values=sin_exp_table(),
            bits=SINEXP_BITS,
            signed=False,
            formula_citation="EngineMkI.cpp:88-92 (dexed b6cf2e9)",
            formula="round(float32((pow(2, float(i)/1024) - 1) * 4096))",
        ),
        "freqlut_table": TableArtifact(
            name="freqlut_table",
            values=freqlut_table(sample_rate),
            bits=FREQLUT_BITS,
            signed=True,
            formula_citation="freqlut.cc:35-42 (dexed b6cf2e9)",
            formula="lut[i] = floor(y + 0.5); y *= 2**(1/1024); "
                    "y0 = 2**44 / 48000.0",
        ),
    }


def manifest(artifacts: dict[str, TableArtifact],
             sample_rate: float = 48000.0) -> dict:
    """Deterministic manifest: {name: {sha256, entries, bits, ...}}."""
    out = {
        "schema": "gf180-dx7/table-manifest-v1",
        "issue": "https://github.com/2AMLogic/gf180-dx7/issues/16",
        "generator": "tools/gen_tables.py",
        "model_contract": "gf180-dx7-integer-v1",
        "sample_rate_hz": int(sample_rate) if float(sample_rate).is_integer()
        else sample_rate,
        "note": "tables REGENERATED from documented formulas (NUM-001); "
                "no bytes copied from the pinned GPL/Apache trees",
        "tables": {},
    }
    for name in sorted(artifacts):
        a = artifacts[name]
        out["tables"][name] = {
            "sha256": a.sha256,
            "entries": a.entries,
            "bits": a.bits,
            "signed": a.signed,
            "file": name + ".hex",
            "formula": a.formula,
            "formula_citation": a.formula_citation,
        }
    return out


def write_tables(out_dir: Path, artifacts: dict[str, TableArtifact],
                 sample_rate: float = 48000.0) -> None:
    """Write <name>.hex + manifest.json deterministically (sorted, LF)."""
    out_dir = Path(out_dir)
    out_dir.mkdir(parents=True, exist_ok=True)
    for name in sorted(artifacts):
        (out_dir / (name + ".hex")).write_text(
            artifacts[name].hex_text(), encoding="ascii")
    text = json.dumps(manifest(artifacts, sample_rate), indent=2,
                      sort_keys=True) + "\n"
    (out_dir / MANIFEST_NAME).write_text(text, encoding="utf-8")


def load_pinned(tables_dir: Path) -> dict[str, TableArtifact]:
    """Load the committed .hex tables and verify every SHA-256 against the
    manifest. Raises TableDrift on any drift (negative control)."""
    tables_dir = Path(tables_dir)
    mpath = tables_dir / MANIFEST_NAME
    if not mpath.is_file():
        raise TableDrift(f"missing table manifest: {mpath}")
    mf = json.loads(mpath.read_text(encoding="utf-8"))
    loaded: dict[str, TableArtifact] = {}
    for name, spec in sorted(mf["tables"].items()):
        hpath = tables_dir / spec["file"]
        if not hpath.is_file():
            raise TableDrift(f"missing pinned table: {hpath}")
        width = spec["bits"] // 4
        raw = hpath.read_text(encoding="ascii")
        values = []
        for lineno, line in enumerate(raw.splitlines(), 1):
            if not line.strip():
                continue
            if len(line.strip()) != width:
                raise TableDrift(
                    f"{hpath}:{lineno}: expected {width} hex digits, got "
                    f"{line.strip()!r}")
            values.append(int(line, 16))
        data = struct.pack("<%d%s" % (len(values),
                                      "i" if spec["signed"] else "H"),
                           *values)
        actual = hashlib.sha256(data).hexdigest()
        if actual != spec["sha256"]:
            raise TableDrift(
                f"{name}: sha256 {actual} != pinned {spec['sha256']} "
                "(table bytes drifted or were hand-edited)")
        if len(values) != spec["entries"]:
            raise TableDrift(
                f"{name}: {len(values)} entries != pinned {spec['entries']}")
        loaded[name] = TableArtifact(
            name=name, values=tuple(values), bits=spec["bits"],
            signed=spec["signed"], formula_citation=spec["formula_citation"],
            formula=spec["formula"])
    return loaded
