// Verilated -*- C++ -*-
// DESCRIPTION: Verilator output: Design internal header
// See Vtb_dx7_core.h for the primary calling header

#ifndef VERILATED_VTB_DX7_CORE___024ROOT_H_
#define VERILATED_VTB_DX7_CORE___024ROOT_H_  // guard

#include "verilated.h"
#include "verilated_timing.h"
class Vtb_dx7_core_env_unit;


class Vtb_dx7_core__Syms;

class alignas(VL_CACHE_LINE_BYTES) Vtb_dx7_core___024root final {
  public:
    // CELLS
    Vtb_dx7_core_env_unit* __PVT__tb_dx7_core__DOT__dut__DOT__envs__BRA__0__KET____DOT__u_env;
    Vtb_dx7_core_env_unit* __PVT__tb_dx7_core__DOT__dut__DOT__envs__BRA__1__KET____DOT__u_env;
    Vtb_dx7_core_env_unit* __PVT__tb_dx7_core__DOT__dut__DOT__envs__BRA__2__KET____DOT__u_env;
    Vtb_dx7_core_env_unit* __PVT__tb_dx7_core__DOT__dut__DOT__envs__BRA__3__KET____DOT__u_env;
    Vtb_dx7_core_env_unit* __PVT__tb_dx7_core__DOT__dut__DOT__envs__BRA__4__KET____DOT__u_env;
    Vtb_dx7_core_env_unit* __PVT__tb_dx7_core__DOT__dut__DOT__envs__BRA__5__KET____DOT__u_env;
    Vtb_dx7_core_env_unit* __PVT__tb_dx7_core__DOT__dut__DOT__envs__BRA__6__KET____DOT__u_env;
    Vtb_dx7_core_env_unit* __PVT__tb_dx7_core__DOT__dut__DOT__envs__BRA__7__KET____DOT__u_env;
    Vtb_dx7_core_env_unit* __PVT__tb_dx7_core__DOT__dut__DOT__envs__BRA__8__KET____DOT__u_env;
    Vtb_dx7_core_env_unit* __PVT__tb_dx7_core__DOT__dut__DOT__envs__BRA__9__KET____DOT__u_env;
    Vtb_dx7_core_env_unit* __PVT__tb_dx7_core__DOT__dut__DOT__envs__BRA__10__KET____DOT__u_env;
    Vtb_dx7_core_env_unit* __PVT__tb_dx7_core__DOT__dut__DOT__envs__BRA__11__KET____DOT__u_env;
    Vtb_dx7_core_env_unit* __PVT__tb_dx7_core__DOT__dut__DOT__envs__BRA__12__KET____DOT__u_env;
    Vtb_dx7_core_env_unit* __PVT__tb_dx7_core__DOT__dut__DOT__envs__BRA__13__KET____DOT__u_env;
    Vtb_dx7_core_env_unit* __PVT__tb_dx7_core__DOT__dut__DOT__envs__BRA__14__KET____DOT__u_env;
    Vtb_dx7_core_env_unit* __PVT__tb_dx7_core__DOT__dut__DOT__envs__BRA__15__KET____DOT__u_env;
    Vtb_dx7_core_env_unit* __PVT__tb_dx7_core__DOT__dut__DOT__envs__BRA__16__KET____DOT__u_env;
    Vtb_dx7_core_env_unit* __PVT__tb_dx7_core__DOT__dut__DOT__envs__BRA__17__KET____DOT__u_env;
    Vtb_dx7_core_env_unit* __PVT__tb_dx7_core__DOT__dut__DOT__envs__BRA__18__KET____DOT__u_env;
    Vtb_dx7_core_env_unit* __PVT__tb_dx7_core__DOT__dut__DOT__envs__BRA__19__KET____DOT__u_env;
    Vtb_dx7_core_env_unit* __PVT__tb_dx7_core__DOT__dut__DOT__envs__BRA__20__KET____DOT__u_env;
    Vtb_dx7_core_env_unit* __PVT__tb_dx7_core__DOT__dut__DOT__envs__BRA__21__KET____DOT__u_env;
    Vtb_dx7_core_env_unit* __PVT__tb_dx7_core__DOT__dut__DOT__envs__BRA__22__KET____DOT__u_env;
    Vtb_dx7_core_env_unit* __PVT__tb_dx7_core__DOT__dut__DOT__envs__BRA__23__KET____DOT__u_env;
    Vtb_dx7_core_env_unit* __PVT__tb_dx7_core__DOT__dut__DOT__envs__BRA__24__KET____DOT__u_env;
    Vtb_dx7_core_env_unit* __PVT__tb_dx7_core__DOT__dut__DOT__envs__BRA__25__KET____DOT__u_env;
    Vtb_dx7_core_env_unit* __PVT__tb_dx7_core__DOT__dut__DOT__envs__BRA__26__KET____DOT__u_env;
    Vtb_dx7_core_env_unit* __PVT__tb_dx7_core__DOT__dut__DOT__envs__BRA__27__KET____DOT__u_env;
    Vtb_dx7_core_env_unit* __PVT__tb_dx7_core__DOT__dut__DOT__envs__BRA__28__KET____DOT__u_env;
    Vtb_dx7_core_env_unit* __PVT__tb_dx7_core__DOT__dut__DOT__envs__BRA__29__KET____DOT__u_env;
    Vtb_dx7_core_env_unit* __PVT__tb_dx7_core__DOT__dut__DOT__envs__BRA__30__KET____DOT__u_env;
    Vtb_dx7_core_env_unit* __PVT__tb_dx7_core__DOT__dut__DOT__envs__BRA__31__KET____DOT__u_env;
    Vtb_dx7_core_env_unit* __PVT__tb_dx7_core__DOT__dut__DOT__envs__BRA__32__KET____DOT__u_env;
    Vtb_dx7_core_env_unit* __PVT__tb_dx7_core__DOT__dut__DOT__envs__BRA__33__KET____DOT__u_env;
    Vtb_dx7_core_env_unit* __PVT__tb_dx7_core__DOT__dut__DOT__envs__BRA__34__KET____DOT__u_env;
    Vtb_dx7_core_env_unit* __PVT__tb_dx7_core__DOT__dut__DOT__envs__BRA__35__KET____DOT__u_env;
    Vtb_dx7_core_env_unit* __PVT__tb_dx7_core__DOT__dut__DOT__envs__BRA__36__KET____DOT__u_env;
    Vtb_dx7_core_env_unit* __PVT__tb_dx7_core__DOT__dut__DOT__envs__BRA__37__KET____DOT__u_env;
    Vtb_dx7_core_env_unit* __PVT__tb_dx7_core__DOT__dut__DOT__envs__BRA__38__KET____DOT__u_env;
    Vtb_dx7_core_env_unit* __PVT__tb_dx7_core__DOT__dut__DOT__envs__BRA__39__KET____DOT__u_env;
    Vtb_dx7_core_env_unit* __PVT__tb_dx7_core__DOT__dut__DOT__envs__BRA__40__KET____DOT__u_env;
    Vtb_dx7_core_env_unit* __PVT__tb_dx7_core__DOT__dut__DOT__envs__BRA__41__KET____DOT__u_env;
    Vtb_dx7_core_env_unit* __PVT__tb_dx7_core__DOT__dut__DOT__envs__BRA__42__KET____DOT__u_env;
    Vtb_dx7_core_env_unit* __PVT__tb_dx7_core__DOT__dut__DOT__envs__BRA__43__KET____DOT__u_env;
    Vtb_dx7_core_env_unit* __PVT__tb_dx7_core__DOT__dut__DOT__envs__BRA__44__KET____DOT__u_env;
    Vtb_dx7_core_env_unit* __PVT__tb_dx7_core__DOT__dut__DOT__envs__BRA__45__KET____DOT__u_env;
    Vtb_dx7_core_env_unit* __PVT__tb_dx7_core__DOT__dut__DOT__envs__BRA__46__KET____DOT__u_env;
    Vtb_dx7_core_env_unit* __PVT__tb_dx7_core__DOT__dut__DOT__envs__BRA__47__KET____DOT__u_env;
    Vtb_dx7_core_env_unit* __PVT__tb_dx7_core__DOT__dut__DOT__envs__BRA__48__KET____DOT__u_env;
    Vtb_dx7_core_env_unit* __PVT__tb_dx7_core__DOT__dut__DOT__envs__BRA__49__KET____DOT__u_env;
    Vtb_dx7_core_env_unit* __PVT__tb_dx7_core__DOT__dut__DOT__envs__BRA__50__KET____DOT__u_env;
    Vtb_dx7_core_env_unit* __PVT__tb_dx7_core__DOT__dut__DOT__envs__BRA__51__KET____DOT__u_env;
    Vtb_dx7_core_env_unit* __PVT__tb_dx7_core__DOT__dut__DOT__envs__BRA__52__KET____DOT__u_env;
    Vtb_dx7_core_env_unit* __PVT__tb_dx7_core__DOT__dut__DOT__envs__BRA__53__KET____DOT__u_env;
    Vtb_dx7_core_env_unit* __PVT__tb_dx7_core__DOT__dut__DOT__envs__BRA__54__KET____DOT__u_env;
    Vtb_dx7_core_env_unit* __PVT__tb_dx7_core__DOT__dut__DOT__envs__BRA__55__KET____DOT__u_env;
    Vtb_dx7_core_env_unit* __PVT__tb_dx7_core__DOT__dut__DOT__envs__BRA__56__KET____DOT__u_env;
    Vtb_dx7_core_env_unit* __PVT__tb_dx7_core__DOT__dut__DOT__envs__BRA__57__KET____DOT__u_env;
    Vtb_dx7_core_env_unit* __PVT__tb_dx7_core__DOT__dut__DOT__envs__BRA__58__KET____DOT__u_env;
    Vtb_dx7_core_env_unit* __PVT__tb_dx7_core__DOT__dut__DOT__envs__BRA__59__KET____DOT__u_env;
    Vtb_dx7_core_env_unit* __PVT__tb_dx7_core__DOT__dut__DOT__envs__BRA__60__KET____DOT__u_env;
    Vtb_dx7_core_env_unit* __PVT__tb_dx7_core__DOT__dut__DOT__envs__BRA__61__KET____DOT__u_env;
    Vtb_dx7_core_env_unit* __PVT__tb_dx7_core__DOT__dut__DOT__envs__BRA__62__KET____DOT__u_env;
    Vtb_dx7_core_env_unit* __PVT__tb_dx7_core__DOT__dut__DOT__envs__BRA__63__KET____DOT__u_env;
    Vtb_dx7_core_env_unit* __PVT__tb_dx7_core__DOT__dut__DOT__envs__BRA__64__KET____DOT__u_env;
    Vtb_dx7_core_env_unit* __PVT__tb_dx7_core__DOT__dut__DOT__envs__BRA__65__KET____DOT__u_env;
    Vtb_dx7_core_env_unit* __PVT__tb_dx7_core__DOT__dut__DOT__envs__BRA__66__KET____DOT__u_env;
    Vtb_dx7_core_env_unit* __PVT__tb_dx7_core__DOT__dut__DOT__envs__BRA__67__KET____DOT__u_env;
    Vtb_dx7_core_env_unit* __PVT__tb_dx7_core__DOT__dut__DOT__envs__BRA__68__KET____DOT__u_env;
    Vtb_dx7_core_env_unit* __PVT__tb_dx7_core__DOT__dut__DOT__envs__BRA__69__KET____DOT__u_env;
    Vtb_dx7_core_env_unit* __PVT__tb_dx7_core__DOT__dut__DOT__envs__BRA__70__KET____DOT__u_env;
    Vtb_dx7_core_env_unit* __PVT__tb_dx7_core__DOT__dut__DOT__envs__BRA__71__KET____DOT__u_env;
    Vtb_dx7_core_env_unit* __PVT__tb_dx7_core__DOT__dut__DOT__envs__BRA__72__KET____DOT__u_env;
    Vtb_dx7_core_env_unit* __PVT__tb_dx7_core__DOT__dut__DOT__envs__BRA__73__KET____DOT__u_env;
    Vtb_dx7_core_env_unit* __PVT__tb_dx7_core__DOT__dut__DOT__envs__BRA__74__KET____DOT__u_env;
    Vtb_dx7_core_env_unit* __PVT__tb_dx7_core__DOT__dut__DOT__envs__BRA__75__KET____DOT__u_env;
    Vtb_dx7_core_env_unit* __PVT__tb_dx7_core__DOT__dut__DOT__envs__BRA__76__KET____DOT__u_env;
    Vtb_dx7_core_env_unit* __PVT__tb_dx7_core__DOT__dut__DOT__envs__BRA__77__KET____DOT__u_env;
    Vtb_dx7_core_env_unit* __PVT__tb_dx7_core__DOT__dut__DOT__envs__BRA__78__KET____DOT__u_env;
    Vtb_dx7_core_env_unit* __PVT__tb_dx7_core__DOT__dut__DOT__envs__BRA__79__KET____DOT__u_env;
    Vtb_dx7_core_env_unit* __PVT__tb_dx7_core__DOT__dut__DOT__envs__BRA__80__KET____DOT__u_env;
    Vtb_dx7_core_env_unit* __PVT__tb_dx7_core__DOT__dut__DOT__envs__BRA__81__KET____DOT__u_env;
    Vtb_dx7_core_env_unit* __PVT__tb_dx7_core__DOT__dut__DOT__envs__BRA__82__KET____DOT__u_env;
    Vtb_dx7_core_env_unit* __PVT__tb_dx7_core__DOT__dut__DOT__envs__BRA__83__KET____DOT__u_env;
    Vtb_dx7_core_env_unit* __PVT__tb_dx7_core__DOT__dut__DOT__envs__BRA__84__KET____DOT__u_env;
    Vtb_dx7_core_env_unit* __PVT__tb_dx7_core__DOT__dut__DOT__envs__BRA__85__KET____DOT__u_env;
    Vtb_dx7_core_env_unit* __PVT__tb_dx7_core__DOT__dut__DOT__envs__BRA__86__KET____DOT__u_env;
    Vtb_dx7_core_env_unit* __PVT__tb_dx7_core__DOT__dut__DOT__envs__BRA__87__KET____DOT__u_env;
    Vtb_dx7_core_env_unit* __PVT__tb_dx7_core__DOT__dut__DOT__envs__BRA__88__KET____DOT__u_env;
    Vtb_dx7_core_env_unit* __PVT__tb_dx7_core__DOT__dut__DOT__envs__BRA__89__KET____DOT__u_env;
    Vtb_dx7_core_env_unit* __PVT__tb_dx7_core__DOT__dut__DOT__envs__BRA__90__KET____DOT__u_env;
    Vtb_dx7_core_env_unit* __PVT__tb_dx7_core__DOT__dut__DOT__envs__BRA__91__KET____DOT__u_env;
    Vtb_dx7_core_env_unit* __PVT__tb_dx7_core__DOT__dut__DOT__envs__BRA__92__KET____DOT__u_env;
    Vtb_dx7_core_env_unit* __PVT__tb_dx7_core__DOT__dut__DOT__envs__BRA__93__KET____DOT__u_env;
    Vtb_dx7_core_env_unit* __PVT__tb_dx7_core__DOT__dut__DOT__envs__BRA__94__KET____DOT__u_env;
    Vtb_dx7_core_env_unit* __PVT__tb_dx7_core__DOT__dut__DOT__envs__BRA__95__KET____DOT__u_env;

    // DESIGN SPECIFIC STATE
    // Anonymous structures to workaround compiler member-count bugs
    struct {
        CData/*0:0*/ tb_dx7_core__DOT__clk;
        CData/*0:0*/ tb_dx7_core__DOT__rst_n;
        CData/*0:0*/ tb_dx7_core__DOT__spi_sck;
        CData/*0:0*/ tb_dx7_core__DOT__spi_mosi;
        CData/*0:0*/ tb_dx7_core__DOT__spi_cs_n;
        CData/*7:0*/ tb_dx7_core__DOT__tok;
        CData/*0:0*/ tb_dx7_core__DOT__lr_d;
        CData/*7:0*/ tb_dx7_core__DOT__c0;
        CData/*7:0*/ tb_dx7_core__DOT__c1;
        CData/*7:0*/ tb_dx7_core__DOT__c2;
        CData/*7:0*/ tb_dx7_core__DOT__c3;
        CData/*7:0*/ tb_dx7_core__DOT__dut__DOT____VlemCall_4__pmsens_tab;
        CData/*0:0*/ tb_dx7_core__DOT__dut__DOT__rst_ff1;
        CData/*0:0*/ tb_dx7_core__DOT__dut__DOT__rst_ff2;
        CData/*5:0*/ tb_dx7_core__DOT__dut__DOT__sample_idx;
        CData/*0:0*/ tb_dx7_core__DOT__dut__DOT__frame_boundary;
        CData/*0:0*/ tb_dx7_core__DOT__dut__DOT__sck_s1;
        CData/*0:0*/ tb_dx7_core__DOT__dut__DOT__sck_s2;
        CData/*0:0*/ tb_dx7_core__DOT__dut__DOT__sck_d;
        CData/*0:0*/ tb_dx7_core__DOT__dut__DOT__mosi_s1;
        CData/*0:0*/ tb_dx7_core__DOT__dut__DOT__mosi_s2;
        CData/*0:0*/ tb_dx7_core__DOT__dut__DOT__cs_s1;
        CData/*0:0*/ tb_dx7_core__DOT__dut__DOT__cs_s2;
        CData/*0:0*/ tb_dx7_core__DOT__dut__DOT__cs_d;
        CData/*0:0*/ tb_dx7_core__DOT__dut__DOT__st_overrun;
        CData/*0:0*/ tb_dx7_core__DOT__dut__DOT__st_overflow;
        CData/*0:0*/ tb_dx7_core__DOT__dut__DOT__st_fresh;
        CData/*2:0*/ tb_dx7_core__DOT__dut__DOT__skid_wp;
        CData/*2:0*/ tb_dx7_core__DOT__dut__DOT__skid_rp;
        CData/*3:0*/ tb_dx7_core__DOT__dut__DOT__skid_cnt;
        CData/*5:0*/ tb_dx7_core__DOT__dut__DOT__bit_cnt;
        CData/*0:0*/ tb_dx7_core__DOT__dut__DOT__frame_reg_v;
        CData/*0:0*/ tb_dx7_core__DOT__dut__DOT__wr_wr;
        CData/*0:0*/ tb_dx7_core__DOT__dut__DOT__shd_commit;
        CData/*7:0*/ tb_dx7_core__DOT__dut__DOT__evq_wp;
        CData/*7:0*/ tb_dx7_core__DOT__dut__DOT__evq_rp;
        CData/*3:0*/ tb_dx7_core__DOT__dut__DOT__cur_note;
        CData/*7:0*/ tb_dx7_core__DOT__dut__DOT__seq_ctr;
        CData/*0:0*/ tb_dx7_core__DOT__dut__DOT__sustain;
        CData/*0:0*/ tb_dx7_core__DOT__dut__DOT__refresh_pending;
        CData/*7:0*/ tb_dx7_core__DOT__dut__DOT__lfo_rand;
        CData/*7:0*/ tb_dx7_core__DOT__dut__DOT__l_a0;
        CData/*7:0*/ tb_dx7_core__DOT__dut__DOT__l_rand_nx;
        CData/*7:0*/ tb_dx7_core__DOT__dut__DOT__peg_tab19__Vstatic__t;
        CData/*0:0*/ tb_dx7_core__DOT__dut__DOT__exp_start;
        CData/*3:0*/ tb_dx7_core__DOT__dut__DOT__exp_st;
        CData/*5:0*/ tb_dx7_core__DOT__dut__DOT__exp_k;
        CData/*5:0*/ tb_dx7_core__DOT__dut__DOT__fc_state;
        CData/*3:0*/ tb_dx7_core__DOT__dut__DOT__nn;
        CData/*2:0*/ tb_dx7_core__DOT__dut__DOT__opk;
        CData/*1:0*/ tb_dx7_core__DOT__dut__DOT__kind;
        CData/*6:0*/ tb_dx7_core__DOT__dut__DOT__stg_note;
        CData/*6:0*/ tb_dx7_core__DOT__dut__DOT__stg_vel;
        CData/*7:0*/ tb_dx7_core__DOT__dut__DOT__stg_ctrl;
        CData/*7:0*/ tb_dx7_core__DOT__dut__DOT__stg_val;
        CData/*3:0*/ tb_dx7_core__DOT__dut__DOT__tgt;
        CData/*3:0*/ tb_dx7_core__DOT__dut__DOT__scan;
        CData/*7:0*/ tb_dx7_core__DOT__dut__DOT__w_pmdep;
        CData/*7:0*/ tb_dx7_core__DOT__dut__DOT__w_pmsens;
        CData/*7:0*/ tb_dx7_core__DOT__dut__DOT__w_amdep;
        CData/*0:0*/ tb_dx7_core__DOT__dut__DOT__r_ld_cfg;
        CData/*0:0*/ tb_dx7_core__DOT__dut__DOT__r_ld_fb;
        CData/*0:0*/ tb_dx7_core__DOT__dut__DOT__r_ld_op;
        CData/*0:0*/ tb_dx7_core__DOT__dut__DOT__r_start;
    };
    struct {
        CData/*4:0*/ tb_dx7_core__DOT__dut__DOT__r_cfg_algorithm;
        CData/*4:0*/ tb_dx7_core__DOT__dut__DOT__r_cfg_feedback;
        CData/*2:0*/ tb_dx7_core__DOT__dut__DOT__r_ld_op_idx;
        CData/*6:0*/ tb_dx7_core__DOT__dut__DOT__r_rd_addr;
        CData/*5:0*/ tb_dx7_core__DOT__dut__DOT__mix_j;
        CData/*2:0*/ tb_dx7_core__DOT__dut__DOT__rb_cnt;
        CData/*6:0*/ tb_dx7_core__DOT__dut__DOT__dv_note;
        CData/*6:0*/ tb_dx7_core__DOT__dut__DOT__dv_r0;
        CData/*6:0*/ tb_dx7_core__DOT__dut__DOT__dv_r1;
        CData/*6:0*/ tb_dx7_core__DOT__dut__DOT__dv_r2;
        CData/*6:0*/ tb_dx7_core__DOT__dut__DOT__dv_r3;
        CData/*0:0*/ tb_dx7_core__DOT__dut__DOT__f0;
        CData/*0:0*/ tb_dx7_core__DOT__dut__DOT__f1;
        CData/*0:0*/ tb_dx7_core__DOT__dut__DOT__f2;
        CData/*0:0*/ tb_dx7_core__DOT__dut__DOT__f3;
        CData/*0:0*/ tb_dx7_core__DOT__dut__DOT__f4;
        CData/*0:0*/ tb_dx7_core__DOT__dut__DOT__f5;
        CData/*0:0*/ tb_dx7_core__DOT__dut__DOT__f6;
        CData/*0:0*/ tb_dx7_core__DOT__dut__DOT__f7;
        CData/*0:0*/ tb_dx7_core__DOT__dut__DOT__f8;
        CData/*0:0*/ tb_dx7_core__DOT__dut__DOT__f9;
        CData/*0:0*/ tb_dx7_core__DOT__dut__DOT__f10;
        CData/*0:0*/ tb_dx7_core__DOT__dut__DOT__f11;
        CData/*0:0*/ tb_dx7_core__DOT__dut__DOT__f12;
        CData/*0:0*/ tb_dx7_core__DOT__dut__DOT__f13;
        CData/*0:0*/ tb_dx7_core__DOT__dut__DOT__f14;
        CData/*0:0*/ tb_dx7_core__DOT__dut__DOT__f15;
        CData/*3:0*/ tb_dx7_core__DOT__dut__DOT__free_idx;
        CData/*3:0*/ tb_dx7_core__DOT__dut__DOT__match_idx;
        CData/*0:0*/ tb_dx7_core__DOT__dut__DOT__match_found;
        CData/*3:0*/ tb_dx7_core__DOT__dut__DOT__steal_idx;
        CData/*0:0*/ tb_dx7_core__DOT__dut__DOT__steal_found;
        CData/*5:0*/ tb_dx7_core__DOT__dut__DOT__dv_rs_eff;
        CData/*7:0*/ tb_dx7_core__DOT__dut__DOT__dv_fine;
        CData/*7:0*/ tb_dx7_core__DOT__dut__DOT__dv_detune;
        CData/*0:0*/ tb_dx7_core__DOT__dut__DOT__t_peg_act;
        CData/*0:0*/ tb_dx7_core__DOT__dut__DOT__t_peg_adv;
        CData/*0:0*/ tb_dx7_core__DOT__dut__DOT__in_sel;
        CData/*0:0*/ tb_dx7_core__DOT__dut__DOT__out_sel;
        CData/*5:0*/ tb_dx7_core__DOT__dut__DOT__tgt_busy;
        CData/*5:0*/ tb_dx7_core__DOT__dut__DOT__scan_busy;
        CData/*1:0*/ tb_dx7_core__DOT__dut__DOT__bclk_div;
        CData/*0:0*/ tb_dx7_core__DOT__dut__DOT__bclk_q;
        CData/*0:0*/ tb_dx7_core__DOT__dut__DOT__lr_q;
        CData/*7:0*/ tb_dx7_core__DOT__dut__DOT__half_cnt;
        CData/*5:0*/ tb_dx7_core__DOT__dut__DOT__falls;
        CData/*5:0*/ tb_dx7_core__DOT__dut__DOT__i2s_smp;
        CData/*0:0*/ tb_dx7_core__DOT__dut__DOT__mix_load;
        CData/*0:0*/ tb_dx7_core__DOT__dut__DOT__obs_q;
        CData/*0:0*/ tb_dx7_core__DOT__dut__DOT__silgen__BRA__0__KET____DOT__s0;
        CData/*0:0*/ tb_dx7_core__DOT__dut__DOT__silgen__BRA__0__KET____DOT__s1;
        CData/*0:0*/ tb_dx7_core__DOT__dut__DOT__silgen__BRA__0__KET____DOT__s2;
        CData/*0:0*/ tb_dx7_core__DOT__dut__DOT__silgen__BRA__0__KET____DOT__s3;
        CData/*0:0*/ tb_dx7_core__DOT__dut__DOT__silgen__BRA__0__KET____DOT__s4;
        CData/*0:0*/ tb_dx7_core__DOT__dut__DOT__silgen__BRA__0__KET____DOT__s5;
        CData/*0:0*/ tb_dx7_core__DOT__dut__DOT__silgen__BRA__1__KET____DOT__s0;
        CData/*0:0*/ tb_dx7_core__DOT__dut__DOT__silgen__BRA__1__KET____DOT__s1;
        CData/*0:0*/ tb_dx7_core__DOT__dut__DOT__silgen__BRA__1__KET____DOT__s2;
        CData/*0:0*/ tb_dx7_core__DOT__dut__DOT__silgen__BRA__1__KET____DOT__s3;
        CData/*0:0*/ tb_dx7_core__DOT__dut__DOT__silgen__BRA__1__KET____DOT__s4;
        CData/*0:0*/ tb_dx7_core__DOT__dut__DOT__silgen__BRA__1__KET____DOT__s5;
        CData/*0:0*/ tb_dx7_core__DOT__dut__DOT__silgen__BRA__2__KET____DOT__s0;
        CData/*0:0*/ tb_dx7_core__DOT__dut__DOT__silgen__BRA__2__KET____DOT__s1;
        CData/*0:0*/ tb_dx7_core__DOT__dut__DOT__silgen__BRA__2__KET____DOT__s2;
    };
    struct {
        CData/*0:0*/ tb_dx7_core__DOT__dut__DOT__silgen__BRA__2__KET____DOT__s3;
        CData/*0:0*/ tb_dx7_core__DOT__dut__DOT__silgen__BRA__2__KET____DOT__s4;
        CData/*0:0*/ tb_dx7_core__DOT__dut__DOT__silgen__BRA__2__KET____DOT__s5;
        CData/*0:0*/ tb_dx7_core__DOT__dut__DOT__silgen__BRA__3__KET____DOT__s0;
        CData/*0:0*/ tb_dx7_core__DOT__dut__DOT__silgen__BRA__3__KET____DOT__s1;
        CData/*0:0*/ tb_dx7_core__DOT__dut__DOT__silgen__BRA__3__KET____DOT__s2;
        CData/*0:0*/ tb_dx7_core__DOT__dut__DOT__silgen__BRA__3__KET____DOT__s3;
        CData/*0:0*/ tb_dx7_core__DOT__dut__DOT__silgen__BRA__3__KET____DOT__s4;
        CData/*0:0*/ tb_dx7_core__DOT__dut__DOT__silgen__BRA__3__KET____DOT__s5;
        CData/*0:0*/ tb_dx7_core__DOT__dut__DOT__silgen__BRA__4__KET____DOT__s0;
        CData/*0:0*/ tb_dx7_core__DOT__dut__DOT__silgen__BRA__4__KET____DOT__s1;
        CData/*0:0*/ tb_dx7_core__DOT__dut__DOT__silgen__BRA__4__KET____DOT__s2;
        CData/*0:0*/ tb_dx7_core__DOT__dut__DOT__silgen__BRA__4__KET____DOT__s3;
        CData/*0:0*/ tb_dx7_core__DOT__dut__DOT__silgen__BRA__4__KET____DOT__s4;
        CData/*0:0*/ tb_dx7_core__DOT__dut__DOT__silgen__BRA__4__KET____DOT__s5;
        CData/*2:0*/ tb_dx7_core__DOT__dut__DOT__u_router__DOT____VlemCall_5__pm;
        CData/*2:0*/ tb_dx7_core__DOT__dut__DOT__u_router__DOT____VlemCall_4__pm;
        CData/*2:0*/ tb_dx7_core__DOT__dut__DOT__u_router__DOT____VlemCall_3__pm;
        CData/*2:0*/ tb_dx7_core__DOT__dut__DOT__u_router__DOT____VlemCall_2__pm;
        CData/*4:0*/ tb_dx7_core__DOT__dut__DOT__u_router__DOT__alg_q;
        CData/*4:0*/ tb_dx7_core__DOT__dut__DOT__u_router__DOT__fbshift_q;
        CData/*0:0*/ tb_dx7_core__DOT__dut__DOT__u_router__DOT__hc0_q;
        CData/*0:0*/ tb_dx7_core__DOT__dut__DOT__u_router__DOT__hc1_q;
        CData/*0:0*/ tb_dx7_core__DOT__dut__DOT__u_router__DOT__hc2_q;
        CData/*2:0*/ tb_dx7_core__DOT__dut__DOT__u_router__DOT__op_q;
        CData/*6:0*/ tb_dx7_core__DOT__dut__DOT__u_router__DOT__i_q;
        CData/*2:0*/ tb_dx7_core__DOT__dut__DOT__u_router__DOT__state_q;
        CData/*0:0*/ tb_dx7_core__DOT__dut__DOT__u_router__DOT__fb_form_q;
        CData/*0:0*/ tb_dx7_core__DOT__dut__DOT__u_router__DOT__ser2_q;
        CData/*0:0*/ tb_dx7_core__DOT__dut__DOT__u_router__DOT__ser3_q;
        CData/*1:0*/ tb_dx7_core__DOT__dut__DOT__u_router__DOT__inbus_q;
        CData/*1:0*/ tb_dx7_core__DOT__dut__DOT__u_router__DOT__outbus_q;
        CData/*0:0*/ tb_dx7_core__DOT__dut__DOT__u_router__DOT__bus_form_q;
        CData/*0:0*/ tb_dx7_core__DOT__dut__DOT__u_router__DOT__add_eff_q;
        CData/*4:0*/ tb_dx7_core__DOT__dut__DOT__u_router__DOT__eff_shift_q;
        CData/*0:0*/ tb_dx7_core__DOT__dut__DOT__u_router__DOT__obs_q;
        CData/*7:0*/ tb_dx7_core__DOT__dut__DOT__u_router__DOT__flags;
        CData/*0:0*/ tb_dx7_core__DOT__dut__DOT__u_router__DOT__gate_pass;
        CData/*0:0*/ tb_dx7_core__DOT__dut__DOT__u_router__DOT__inbus_live;
        CData/*0:0*/ tb_dx7_core__DOT__dut__DOT__u_router__DOT__fb_dispatch;
        CData/*0:0*/ tb_dx7_core__DOT__dut__DOT__u_router__DOT__ser3_sel;
        CData/*0:0*/ tb_dx7_core__DOT__dut__DOT__u_router__DOT__ser2_sel;
        CData/*7:0*/ __VdfgRegularize_hebeb780c_0_0;
        CData/*0:0*/ __VdfgRegularize_hebeb780c_0_1;
        CData/*7:0*/ __VdfgRegularize_hebeb780c_0_23;
        CData/*3:0*/ __Vdly__tb_dx7_core__DOT__dut__DOT__skid_cnt;
        CData/*7:0*/ __Vdly__tb_dx7_core__DOT__dut__DOT__evq_rp;
        CData/*0:0*/ __Vdly__tb_dx7_core__DOT__dut__DOT__shd_commit;
        CData/*3:0*/ __Vdly__tb_dx7_core__DOT__dut__DOT__exp_st;
        CData/*5:0*/ __Vdly__tb_dx7_core__DOT__dut__DOT__exp_k;
        CData/*5:0*/ __Vdly__tb_dx7_core__DOT__dut__DOT__fc_state;
        CData/*3:0*/ __Vdly__tb_dx7_core__DOT__dut__DOT__nn;
        CData/*2:0*/ __Vdly__tb_dx7_core__DOT__dut__DOT__opk;
        CData/*3:0*/ __Vdly__tb_dx7_core__DOT__dut__DOT__tgt;
        CData/*3:0*/ __Vdly__tb_dx7_core__DOT__dut__DOT__scan;
        CData/*1:0*/ __Vdly__tb_dx7_core__DOT__dut__DOT__kind;
        CData/*7:0*/ __Vdly__tb_dx7_core__DOT__dut__DOT__seq_ctr;
        CData/*0:0*/ __Vdly__tb_dx7_core__DOT__dut__DOT__sustain;
        CData/*0:0*/ __Vdly__tb_dx7_core__DOT__dut__DOT__refresh_pending;
        CData/*0:0*/ __Vdly__tb_dx7_core__DOT__dut__DOT__in_sel;
        CData/*7:0*/ __Vdly__tb_dx7_core__DOT__dut__DOT__lfo_rand;
        CData/*0:0*/ __Vdly__tb_dx7_core__DOT__dut__DOT__exp_start;
        CData/*6:0*/ __Vdly__tb_dx7_core__DOT__dut__DOT__stg_note;
        CData/*6:0*/ __Vdly__tb_dx7_core__DOT__dut__DOT__stg_vel;
    };
    struct {
        CData/*6:0*/ __Vdly__tb_dx7_core__DOT__dut__DOT__r_rd_addr;
        CData/*2:0*/ __Vdly__tb_dx7_core__DOT__dut__DOT__u_router__DOT__state_q;
        CData/*0:0*/ __VdlySet__tb_dx7_core__DOT__dut__DOT__shd_opitch__v0;
        CData/*2:0*/ __VdlyDim0__tb_dx7_core__DOT__dut__DOT__shd_opitch__v6;
        CData/*0:0*/ __VdlySet__tb_dx7_core__DOT__dut__DOT__shd_opitch__v6;
        CData/*0:0*/ __VdlySet__tb_dx7_core__DOT__dut__DOT__shd_fterm__v0;
        CData/*2:0*/ __VdlyDim0__tb_dx7_core__DOT__dut__DOT__shd_fterm__v6;
        CData/*0:0*/ __VdlySet__tb_dx7_core__DOT__dut__DOT__shd_fterm__v6;
        CData/*0:0*/ __VdlySet__tb_dx7_core__DOT__dut__DOT__shd_erates__v0;
        CData/*2:0*/ __VdlyDim0__tb_dx7_core__DOT__dut__DOT__shd_erates__v6;
        CData/*0:0*/ __VdlySet__tb_dx7_core__DOT__dut__DOT__shd_erates__v6;
        CData/*0:0*/ __VdlySet__tb_dx7_core__DOT__dut__DOT__shd_elevels__v0;
        CData/*2:0*/ __VdlyDim0__tb_dx7_core__DOT__dut__DOT__shd_elevels__v6;
        CData/*0:0*/ __VdlySet__tb_dx7_core__DOT__dut__DOT__shd_elevels__v6;
        CData/*0:0*/ __VdlySet__tb_dx7_core__DOT__dut__DOT__shd_scaleA__v0;
        CData/*2:0*/ __VdlyDim0__tb_dx7_core__DOT__dut__DOT__shd_scaleA__v6;
        CData/*0:0*/ __VdlySet__tb_dx7_core__DOT__dut__DOT__shd_scaleA__v6;
        CData/*0:0*/ __VdlySet__tb_dx7_core__DOT__dut__DOT__shd_scaleB__v0;
        CData/*2:0*/ __VdlyDim0__tb_dx7_core__DOT__dut__DOT__shd_scaleB__v6;
        CData/*0:0*/ __VdlySet__tb_dx7_core__DOT__dut__DOT__shd_scaleB__v6;
        CData/*0:0*/ __VdlySet__tb_dx7_core__DOT__dut__DOT__cmt_opitch__v0;
        CData/*0:0*/ __VdlySet__tb_dx7_core__DOT__dut__DOT__n_midi__v0;
        CData/*0:0*/ __VdlySet__tb_dx7_core__DOT__dut__DOT__cmt_opitch__v1;
        CData/*0:0*/ __VdlySet__tb_dx7_core__DOT__dut__DOT__op_li__v96;
        CData/*0:0*/ __VdlySet__tb_dx7_core__DOT__dut__DOT__env_cmd__v0;
        CData/*0:0*/ __VdlySet__tb_dx7_core__DOT__dut__DOT__env_cmd_data__v0;
        CData/*0:0*/ __VdlySet__tb_dx7_core__DOT__dut__DOT__env_cmd__v1;
        CData/*0:0*/ __VdlySet__tb_dx7_core__DOT__dut__DOT__env_cmd_data__v1;
        CData/*0:0*/ __VdlySet__tb_dx7_core__DOT__dut__DOT__env_cmd__v2;
        CData/*0:0*/ __VdlySet__tb_dx7_core__DOT__dut__DOT__env_cmd_data__v2;
        CData/*0:0*/ __VdlySet__tb_dx7_core__DOT__dut__DOT__env_cmd__v3;
        CData/*0:0*/ __VdlySet__tb_dx7_core__DOT__dut__DOT__env_cmd_data__v3;
        CData/*0:0*/ __VdlySet__tb_dx7_core__DOT__dut__DOT__env_cmd__v4;
        CData/*0:0*/ __VdlySet__tb_dx7_core__DOT__dut__DOT__env_cmd_data__v4;
        CData/*0:0*/ __VdlySet__tb_dx7_core__DOT__dut__DOT__env_cmd__v5;
        CData/*0:0*/ __VdlySet__tb_dx7_core__DOT__dut__DOT__env_cmd_data__v5;
        CData/*0:0*/ __VdlySet__tb_dx7_core__DOT__dut__DOT__env_cmd__v6;
        CData/*0:0*/ __VdlySet__tb_dx7_core__DOT__dut__DOT__env_cmd__v7;
        CData/*0:0*/ __VdlySet__tb_dx7_core__DOT__dut__DOT__env_cmd__v8;
        CData/*0:0*/ __VdlySet__tb_dx7_core__DOT__dut__DOT__env_cmd__v9;
        CData/*0:0*/ __VdlySet__tb_dx7_core__DOT__dut__DOT__env_cmd__v10;
        CData/*0:0*/ __VdlySet__tb_dx7_core__DOT__dut__DOT__env_cmd__v11;
        CData/*0:0*/ __VdlySet__tb_dx7_core__DOT__dut__DOT__n_bp__v96;
        CData/*0:0*/ __VdlySet__tb_dx7_core__DOT__dut__DOT__n_opmode__v16;
        CData/*0:0*/ __VdlySet__tb_dx7_core__DOT__dut__DOT__n_alg__v16;
        CData/*0:0*/ __VdlySet__tb_dx7_core__DOT__dut__DOT__n_fbs__v16;
        CData/*0:0*/ __VdlySet__tb_dx7_core__DOT__dut__DOT__n_pmsens__v16;
        CData/*0:0*/ __VdlySet__tb_dx7_core__DOT__dut__DOT__n_ams__v96;
        CData/*0:0*/ __VdlySet__tb_dx7_core__DOT__dut__DOT__n_ams__v97;
        CData/*0:0*/ __VdlySet__tb_dx7_core__DOT__dut__DOT__n_ams__v98;
        CData/*0:0*/ __VdlySet__tb_dx7_core__DOT__dut__DOT__n_ams__v99;
        CData/*0:0*/ __VdlySet__tb_dx7_core__DOT__dut__DOT__n_ams__v100;
        CData/*0:0*/ __VdlySet__tb_dx7_core__DOT__dut__DOT__n_ams__v101;
        CData/*0:0*/ __VdlySet__tb_dx7_core__DOT__dut__DOT__n_sil__v16;
        CData/*6:0*/ __VdlyVal__tb_dx7_core__DOT__dut__DOT__n_sil__v17;
        CData/*0:0*/ __VdlySet__tb_dx7_core__DOT__dut__DOT__n_sil__v17;
        CData/*0:0*/ __VdlySet__tb_dx7_core__DOT__dut__DOT__n_sil__v18;
        CData/*0:0*/ __VdlySet__tb_dx7_core__DOT__dut__DOT__n_sil__v19;
        CData/*0:0*/ __VdlySet__tb_dx7_core__DOT__dut__DOT__n_sil__v20;
        CData/*6:0*/ __VdlyVal__tb_dx7_core__DOT__dut__DOT__n_sil__v21;
        CData/*0:0*/ __VdlySet__tb_dx7_core__DOT__dut__DOT__n_sil__v21;
        CData/*0:0*/ __VdlySet__tb_dx7_core__DOT__dut__DOT__n_sil__v22;
        CData/*0:0*/ __VdlySet__tb_dx7_core__DOT__dut__DOT__n_sil__v23;
        CData/*0:0*/ __VdlySet__tb_dx7_core__DOT__dut__DOT__n_sil__v24;
    };
    struct {
        CData/*6:0*/ __VdlyVal__tb_dx7_core__DOT__dut__DOT__n_sil__v25;
        CData/*0:0*/ __VdlySet__tb_dx7_core__DOT__dut__DOT__n_sil__v25;
        CData/*0:0*/ __VdlySet__tb_dx7_core__DOT__dut__DOT__n_sil__v26;
        CData/*0:0*/ __VdlySet__tb_dx7_core__DOT__dut__DOT__n_sil__v27;
        CData/*0:0*/ __VdlySet__tb_dx7_core__DOT__dut__DOT__n_sil__v28;
        CData/*6:0*/ __VdlyVal__tb_dx7_core__DOT__dut__DOT__n_sil__v29;
        CData/*0:0*/ __VdlySet__tb_dx7_core__DOT__dut__DOT__n_sil__v29;
        CData/*0:0*/ __VdlySet__tb_dx7_core__DOT__dut__DOT__n_sil__v30;
        CData/*0:0*/ __VdlySet__tb_dx7_core__DOT__dut__DOT__n_sil__v31;
        CData/*0:0*/ __VdlySet__tb_dx7_core__DOT__dut__DOT__n_sil__v32;
        CData/*6:0*/ __VdlyVal__tb_dx7_core__DOT__dut__DOT__n_sil__v33;
        CData/*0:0*/ __VdlySet__tb_dx7_core__DOT__dut__DOT__n_sil__v33;
        CData/*0:0*/ __VdlySet__tb_dx7_core__DOT__dut__DOT__n_sil__v34;
        CData/*0:0*/ __VdlySet__tb_dx7_core__DOT__dut__DOT__n_sil__v35;
        CData/*0:0*/ __VdlySet__tb_dx7_core__DOT__dut__DOT__n_sil__v36;
        CData/*6:0*/ __VdlyVal__tb_dx7_core__DOT__dut__DOT__n_sil__v37;
        CData/*0:0*/ __VdlySet__tb_dx7_core__DOT__dut__DOT__n_sil__v37;
        CData/*0:0*/ __VdlySet__tb_dx7_core__DOT__dut__DOT__n_sil__v38;
        CData/*0:0*/ __VdlySet__tb_dx7_core__DOT__dut__DOT__n_sil__v39;
        CData/*0:0*/ __VdlySet__tb_dx7_core__DOT__dut__DOT__n_sil__v40;
        CData/*6:0*/ __VdlyVal__tb_dx7_core__DOT__dut__DOT__n_sil__v41;
        CData/*0:0*/ __VdlySet__tb_dx7_core__DOT__dut__DOT__n_sil__v41;
        CData/*0:0*/ __VdlySet__tb_dx7_core__DOT__dut__DOT__n_sil__v42;
        CData/*0:0*/ __VdlySet__tb_dx7_core__DOT__dut__DOT__n_sil__v43;
        CData/*0:0*/ __VdlySet__tb_dx7_core__DOT__dut__DOT__n_sil__v44;
        CData/*6:0*/ __VdlyVal__tb_dx7_core__DOT__dut__DOT__n_sil__v45;
        CData/*0:0*/ __VdlySet__tb_dx7_core__DOT__dut__DOT__n_sil__v45;
        CData/*0:0*/ __VdlySet__tb_dx7_core__DOT__dut__DOT__n_sil__v46;
        CData/*0:0*/ __VdlySet__tb_dx7_core__DOT__dut__DOT__n_sil__v47;
        CData/*0:0*/ __VdlySet__tb_dx7_core__DOT__dut__DOT__n_sil__v48;
        CData/*6:0*/ __VdlyVal__tb_dx7_core__DOT__dut__DOT__n_sil__v49;
        CData/*0:0*/ __VdlySet__tb_dx7_core__DOT__dut__DOT__n_sil__v49;
        CData/*0:0*/ __VdlySet__tb_dx7_core__DOT__dut__DOT__n_sil__v50;
        CData/*0:0*/ __VdlySet__tb_dx7_core__DOT__dut__DOT__n_sil__v51;
        CData/*0:0*/ __VdlySet__tb_dx7_core__DOT__dut__DOT__n_sil__v52;
        CData/*6:0*/ __VdlyVal__tb_dx7_core__DOT__dut__DOT__n_sil__v53;
        CData/*0:0*/ __VdlySet__tb_dx7_core__DOT__dut__DOT__n_sil__v53;
        CData/*0:0*/ __VdlySet__tb_dx7_core__DOT__dut__DOT__n_sil__v54;
        CData/*0:0*/ __VdlySet__tb_dx7_core__DOT__dut__DOT__n_sil__v55;
        CData/*0:0*/ __VdlySet__tb_dx7_core__DOT__dut__DOT__n_sil__v56;
        CData/*6:0*/ __VdlyVal__tb_dx7_core__DOT__dut__DOT__n_sil__v57;
        CData/*0:0*/ __VdlySet__tb_dx7_core__DOT__dut__DOT__n_sil__v57;
        CData/*0:0*/ __VdlySet__tb_dx7_core__DOT__dut__DOT__n_sil__v58;
        CData/*0:0*/ __VdlySet__tb_dx7_core__DOT__dut__DOT__n_sil__v59;
        CData/*0:0*/ __VdlySet__tb_dx7_core__DOT__dut__DOT__n_sil__v60;
        CData/*6:0*/ __VdlyVal__tb_dx7_core__DOT__dut__DOT__n_sil__v61;
        CData/*0:0*/ __VdlySet__tb_dx7_core__DOT__dut__DOT__n_sil__v61;
        CData/*0:0*/ __VdlySet__tb_dx7_core__DOT__dut__DOT__n_sil__v62;
        CData/*0:0*/ __VdlySet__tb_dx7_core__DOT__dut__DOT__n_sil__v63;
        CData/*0:0*/ __VdlySet__tb_dx7_core__DOT__dut__DOT__n_sil__v64;
        CData/*6:0*/ __VdlyVal__tb_dx7_core__DOT__dut__DOT__n_sil__v65;
        CData/*0:0*/ __VdlySet__tb_dx7_core__DOT__dut__DOT__n_sil__v65;
        CData/*0:0*/ __VdlySet__tb_dx7_core__DOT__dut__DOT__n_sil__v66;
        CData/*0:0*/ __VdlySet__tb_dx7_core__DOT__dut__DOT__n_sil__v67;
        CData/*0:0*/ __VdlySet__tb_dx7_core__DOT__dut__DOT__n_sil__v68;
        CData/*6:0*/ __VdlyVal__tb_dx7_core__DOT__dut__DOT__n_sil__v69;
        CData/*0:0*/ __VdlySet__tb_dx7_core__DOT__dut__DOT__n_sil__v69;
        CData/*0:0*/ __VdlySet__tb_dx7_core__DOT__dut__DOT__n_sil__v70;
        CData/*0:0*/ __VdlySet__tb_dx7_core__DOT__dut__DOT__n_sil__v71;
        CData/*0:0*/ __VdlySet__tb_dx7_core__DOT__dut__DOT__n_sil__v72;
        CData/*6:0*/ __VdlyVal__tb_dx7_core__DOT__dut__DOT__n_sil__v73;
        CData/*0:0*/ __VdlySet__tb_dx7_core__DOT__dut__DOT__n_sil__v73;
        CData/*0:0*/ __VdlySet__tb_dx7_core__DOT__dut__DOT__n_sil__v74;
        CData/*0:0*/ __VdlySet__tb_dx7_core__DOT__dut__DOT__n_sil__v75;
    };
    struct {
        CData/*0:0*/ __VdlySet__tb_dx7_core__DOT__dut__DOT__n_sil__v76;
        CData/*6:0*/ __VdlyVal__tb_dx7_core__DOT__dut__DOT__n_sil__v77;
        CData/*0:0*/ __VdlySet__tb_dx7_core__DOT__dut__DOT__n_sil__v77;
        CData/*0:0*/ __VdlySet__tb_dx7_core__DOT__dut__DOT__n_sil__v78;
        CData/*0:0*/ __VdlySet__tb_dx7_core__DOT__dut__DOT__n_sil__v79;
        CData/*0:0*/ __VdlySet__tb_dx7_core__DOT__dut__DOT__op_ph__v96;
        CData/*2:0*/ __VdlyDim0__tb_dx7_core__DOT__dut__DOT__op_go__v96;
        CData/*3:0*/ __VdlyDim1__tb_dx7_core__DOT__dut__DOT__op_go__v96;
        CData/*0:0*/ __VdlySet__tb_dx7_core__DOT__dut__DOT__op_go__v96;
        CData/*0:0*/ __VdlySet__tb_dx7_core__DOT__dut__DOT__n_fb0__v16;
        CData/*0:0*/ __VdlySet__tb_dx7_core__DOT__dut__DOT__n_fb1__v16;
        CData/*5:0*/ __VdlyDim0__tb_dx7_core__DOT__dut__DOT__mixbuf__v1152;
        CData/*0:0*/ __VdlyDim1__tb_dx7_core__DOT__dut__DOT__mixbuf__v1152;
        CData/*0:0*/ __VdlySet__tb_dx7_core__DOT__dut__DOT__mixbuf__v1152;
        CData/*0:0*/ __VdlySet__tb_dx7_core__DOT__dut__DOT__op_fq__v96;
        CData/*0:0*/ __VdlySet__tb_dx7_core__DOT__dut__DOT__n_pegix__v16;
        CData/*3:0*/ __VdlyDim0__tb_dx7_core__DOT__dut__DOT__n_pegtgt__v16;
        CData/*0:0*/ __VdlySet__tb_dx7_core__DOT__dut__DOT__n_pegtgt__v16;
        CData/*0:0*/ __VdlyVal__tb_dx7_core__DOT__dut__DOT__n_pegris__v16;
        CData/*3:0*/ __VdlyDim0__tb_dx7_core__DOT__dut__DOT__n_pegris__v16;
        CData/*0:0*/ __VdlySet__tb_dx7_core__DOT__dut__DOT__n_pegris__v16;
        CData/*3:0*/ __VdlyDim0__tb_dx7_core__DOT__dut__DOT__n_peginc__v16;
        CData/*0:0*/ __VdlySet__tb_dx7_core__DOT__dut__DOT__n_peginc__v16;
        CData/*0:0*/ __VdlySet__tb_dx7_core__DOT__dut__DOT__env_cmd__v12;
        CData/*0:0*/ __VdlySet__tb_dx7_core__DOT__dut__DOT__env_cmd__v13;
        CData/*0:0*/ __VdlySet__tb_dx7_core__DOT__dut__DOT__env_cmd_data__v6;
        CData/*0:0*/ __VdlySet__tb_dx7_core__DOT__dut__DOT__n_sil__v80;
        CData/*0:0*/ __VdlyDim1__tb_dx7_core__DOT__dut__DOT__mixbuf__v1153;
        CData/*0:0*/ __VdlySet__tb_dx7_core__DOT__dut__DOT__n_bp__v98;
        CData/*0:0*/ __VdlyDim1__tb_dx7_core__DOT__dut__DOT__mixbuf__v1154;
        CData/*0:0*/ __VdlyDim1__tb_dx7_core__DOT__dut__DOT__mixbuf__v1155;
        CData/*0:0*/ __VdlyDim1__tb_dx7_core__DOT__dut__DOT__mixbuf__v1156;
        CData/*0:0*/ __VdlyDim1__tb_dx7_core__DOT__dut__DOT__mixbuf__v1157;
        CData/*0:0*/ __VdlyDim1__tb_dx7_core__DOT__dut__DOT__mixbuf__v1158;
        CData/*0:0*/ __VdlyDim1__tb_dx7_core__DOT__dut__DOT__mixbuf__v1159;
        CData/*0:0*/ __VdlyDim1__tb_dx7_core__DOT__dut__DOT__mixbuf__v1160;
        CData/*0:0*/ __VdlyDim1__tb_dx7_core__DOT__dut__DOT__mixbuf__v1161;
        CData/*0:0*/ __VdlyDim1__tb_dx7_core__DOT__dut__DOT__mixbuf__v1162;
        CData/*0:0*/ __VdlyDim1__tb_dx7_core__DOT__dut__DOT__mixbuf__v1163;
        CData/*0:0*/ __VdlyDim1__tb_dx7_core__DOT__dut__DOT__mixbuf__v1164;
        CData/*0:0*/ __VdlyDim1__tb_dx7_core__DOT__dut__DOT__mixbuf__v1165;
        CData/*0:0*/ __VdlyDim1__tb_dx7_core__DOT__dut__DOT__mixbuf__v1166;
        CData/*0:0*/ __VdlyDim1__tb_dx7_core__DOT__dut__DOT__mixbuf__v1167;
        CData/*0:0*/ __VdlyDim1__tb_dx7_core__DOT__dut__DOT__mixbuf__v1168;
        CData/*0:0*/ __VdlyDim1__tb_dx7_core__DOT__dut__DOT__mixbuf__v1169;
        CData/*0:0*/ __VdlyDim1__tb_dx7_core__DOT__dut__DOT__mixbuf__v1170;
        CData/*0:0*/ __VdlyDim1__tb_dx7_core__DOT__dut__DOT__mixbuf__v1171;
        CData/*0:0*/ __VdlyDim1__tb_dx7_core__DOT__dut__DOT__mixbuf__v1172;
        CData/*0:0*/ __VdlyDim1__tb_dx7_core__DOT__dut__DOT__mixbuf__v1173;
        CData/*0:0*/ __VdlyDim1__tb_dx7_core__DOT__dut__DOT__mixbuf__v1174;
        CData/*0:0*/ __VdlyDim1__tb_dx7_core__DOT__dut__DOT__mixbuf__v1175;
        CData/*0:0*/ __VdlyDim1__tb_dx7_core__DOT__dut__DOT__mixbuf__v1176;
        CData/*0:0*/ __VdlyDim1__tb_dx7_core__DOT__dut__DOT__mixbuf__v1177;
        CData/*0:0*/ __VdlyDim1__tb_dx7_core__DOT__dut__DOT__mixbuf__v1178;
        CData/*0:0*/ __VdlyDim1__tb_dx7_core__DOT__dut__DOT__mixbuf__v1179;
        CData/*0:0*/ __VdlyDim1__tb_dx7_core__DOT__dut__DOT__mixbuf__v1180;
        CData/*0:0*/ __VdlyDim1__tb_dx7_core__DOT__dut__DOT__mixbuf__v1181;
        CData/*0:0*/ __VdlyDim1__tb_dx7_core__DOT__dut__DOT__mixbuf__v1182;
        CData/*0:0*/ __VdlyDim1__tb_dx7_core__DOT__dut__DOT__mixbuf__v1183;
        CData/*0:0*/ __VdlyDim1__tb_dx7_core__DOT__dut__DOT__mixbuf__v1184;
        CData/*0:0*/ __VdlyDim1__tb_dx7_core__DOT__dut__DOT__mixbuf__v1185;
        CData/*0:0*/ __VdlyDim1__tb_dx7_core__DOT__dut__DOT__mixbuf__v1186;
        CData/*0:0*/ __VdlyDim1__tb_dx7_core__DOT__dut__DOT__mixbuf__v1187;
        CData/*0:0*/ __VdlyDim1__tb_dx7_core__DOT__dut__DOT__mixbuf__v1188;
    };
    struct {
        CData/*0:0*/ __VdlyDim1__tb_dx7_core__DOT__dut__DOT__mixbuf__v1189;
        CData/*0:0*/ __VdlyDim1__tb_dx7_core__DOT__dut__DOT__mixbuf__v1190;
        CData/*0:0*/ __VdlyDim1__tb_dx7_core__DOT__dut__DOT__mixbuf__v1191;
        CData/*0:0*/ __VdlyDim1__tb_dx7_core__DOT__dut__DOT__mixbuf__v1192;
        CData/*0:0*/ __VdlyDim1__tb_dx7_core__DOT__dut__DOT__mixbuf__v1193;
        CData/*0:0*/ __VdlyDim1__tb_dx7_core__DOT__dut__DOT__mixbuf__v1194;
        CData/*0:0*/ __VdlyDim1__tb_dx7_core__DOT__dut__DOT__mixbuf__v1195;
        CData/*0:0*/ __VdlyDim1__tb_dx7_core__DOT__dut__DOT__mixbuf__v1196;
        CData/*0:0*/ __VdlyDim1__tb_dx7_core__DOT__dut__DOT__mixbuf__v1197;
        CData/*0:0*/ __VdlyDim1__tb_dx7_core__DOT__dut__DOT__mixbuf__v1198;
        CData/*0:0*/ __VdlyDim1__tb_dx7_core__DOT__dut__DOT__mixbuf__v1199;
        CData/*0:0*/ __VdlyDim1__tb_dx7_core__DOT__dut__DOT__mixbuf__v1200;
        CData/*0:0*/ __VdlyDim1__tb_dx7_core__DOT__dut__DOT__mixbuf__v1201;
        CData/*0:0*/ __VdlyDim1__tb_dx7_core__DOT__dut__DOT__mixbuf__v1202;
        CData/*0:0*/ __VdlyDim1__tb_dx7_core__DOT__dut__DOT__mixbuf__v1203;
        CData/*0:0*/ __VdlyDim1__tb_dx7_core__DOT__dut__DOT__mixbuf__v1204;
        CData/*0:0*/ __VdlyDim1__tb_dx7_core__DOT__dut__DOT__mixbuf__v1205;
        CData/*0:0*/ __VdlyDim1__tb_dx7_core__DOT__dut__DOT__mixbuf__v1206;
        CData/*0:0*/ __VdlyDim1__tb_dx7_core__DOT__dut__DOT__mixbuf__v1207;
        CData/*0:0*/ __VdlyDim1__tb_dx7_core__DOT__dut__DOT__mixbuf__v1208;
        CData/*0:0*/ __VdlyDim1__tb_dx7_core__DOT__dut__DOT__mixbuf__v1209;
        CData/*0:0*/ __VdlyDim1__tb_dx7_core__DOT__dut__DOT__mixbuf__v1210;
        CData/*0:0*/ __VdlyDim1__tb_dx7_core__DOT__dut__DOT__mixbuf__v1211;
        CData/*0:0*/ __VdlyDim1__tb_dx7_core__DOT__dut__DOT__mixbuf__v1212;
        CData/*0:0*/ __VdlyDim1__tb_dx7_core__DOT__dut__DOT__mixbuf__v1213;
        CData/*0:0*/ __VdlyDim1__tb_dx7_core__DOT__dut__DOT__mixbuf__v1214;
        CData/*0:0*/ __VdlyDim1__tb_dx7_core__DOT__dut__DOT__mixbuf__v1215;
        CData/*0:0*/ __VdlyDim1__tb_dx7_core__DOT__dut__DOT__mixbuf__v1216;
        CData/*0:0*/ __VdlySet__tb_dx7_core__DOT__dut__DOT__env_cmd__v14;
        CData/*0:0*/ __VdlySet__tb_dx7_core__DOT__dut__DOT__env_cmd_data__v7;
        CData/*0:0*/ __VdlySet__tb_dx7_core__DOT__dut__DOT__env_cmd__v15;
        CData/*0:0*/ __VdlySet__tb_dx7_core__DOT__dut__DOT__env_cmd_data__v8;
        CData/*0:0*/ __VdlySet__tb_dx7_core__DOT__dut__DOT__env_cmd__v16;
        CData/*0:0*/ __VdlySet__tb_dx7_core__DOT__dut__DOT__env_cmd_data__v9;
        CData/*0:0*/ __VdlySet__tb_dx7_core__DOT__dut__DOT__env_cmd__v17;
        CData/*0:0*/ __VdlySet__tb_dx7_core__DOT__dut__DOT__env_cmd_data__v10;
        CData/*0:0*/ __VdlySet__tb_dx7_core__DOT__dut__DOT__env_cmd__v18;
        CData/*0:0*/ __VdlySet__tb_dx7_core__DOT__dut__DOT__env_cmd_data__v11;
        CData/*0:0*/ __VdlySet__tb_dx7_core__DOT__dut__DOT__env_cmd__v19;
        CData/*0:0*/ __VdlySet__tb_dx7_core__DOT__dut__DOT__env_cmd_data__v12;
        CData/*0:0*/ __VdlySet__tb_dx7_core__DOT__dut__DOT__n_pegdwn__v32;
        CData/*3:0*/ __VdlyDim0__tb_dx7_core__DOT__dut__DOT__n_pegtgt__v33;
        CData/*0:0*/ __VdlySet__tb_dx7_core__DOT__dut__DOT__n_pegtgt__v33;
        CData/*0:0*/ __VdlyVal__tb_dx7_core__DOT__dut__DOT__n_pegris__v33;
        CData/*3:0*/ __VdlyDim0__tb_dx7_core__DOT__dut__DOT__n_pegris__v33;
        CData/*0:0*/ __VdlySet__tb_dx7_core__DOT__dut__DOT__n_pegris__v33;
        CData/*3:0*/ __VdlyDim0__tb_dx7_core__DOT__dut__DOT__n_peginc__v33;
        CData/*0:0*/ __VdlySet__tb_dx7_core__DOT__dut__DOT__n_peginc__v33;
        CData/*0:0*/ __VdlySet__tb_dx7_core__DOT__dut__DOT__env_cmd__v20;
        CData/*0:0*/ __VdlySet__tb_dx7_core__DOT__dut__DOT__env_cmd_data__v13;
        CData/*0:0*/ __VdlySet__tb_dx7_core__DOT__dut__DOT__env_cmd__v21;
        CData/*0:0*/ __VdlySet__tb_dx7_core__DOT__dut__DOT__env_cmd_data__v14;
        CData/*0:0*/ __VdlySet__tb_dx7_core__DOT__dut__DOT__env_cmd__v22;
        CData/*0:0*/ __VdlySet__tb_dx7_core__DOT__dut__DOT__env_cmd_data__v15;
        CData/*0:0*/ __VdlySet__tb_dx7_core__DOT__dut__DOT__env_cmd__v23;
        CData/*0:0*/ __VdlySet__tb_dx7_core__DOT__dut__DOT__env_cmd_data__v16;
        CData/*0:0*/ __VdlySet__tb_dx7_core__DOT__dut__DOT__env_cmd__v24;
        CData/*0:0*/ __VdlySet__tb_dx7_core__DOT__dut__DOT__env_cmd_data__v17;
        CData/*0:0*/ __VdlySet__tb_dx7_core__DOT__dut__DOT__env_cmd__v25;
        CData/*0:0*/ __VdlySet__tb_dx7_core__DOT__dut__DOT__env_cmd_data__v18;
        CData/*0:0*/ __VdlySet__tb_dx7_core__DOT__dut__DOT__n_pegdwn__v33;
        CData/*3:0*/ __VdlyDim0__tb_dx7_core__DOT__dut__DOT__n_pegtgt__v34;
        CData/*0:0*/ __VdlySet__tb_dx7_core__DOT__dut__DOT__n_pegtgt__v34;
        CData/*0:0*/ __VdlyVal__tb_dx7_core__DOT__dut__DOT__n_pegris__v34;
    };
    struct {
        CData/*3:0*/ __VdlyDim0__tb_dx7_core__DOT__dut__DOT__n_pegris__v34;
        CData/*0:0*/ __VdlySet__tb_dx7_core__DOT__dut__DOT__n_pegris__v34;
        CData/*3:0*/ __VdlyDim0__tb_dx7_core__DOT__dut__DOT__n_peginc__v34;
        CData/*0:0*/ __VdlySet__tb_dx7_core__DOT__dut__DOT__n_peginc__v34;
        CData/*0:0*/ __VdlySet__tb_dx7_core__DOT__dut__DOT__env_cmd__v26;
        CData/*0:0*/ __VdlySet__tb_dx7_core__DOT__dut__DOT__env_cmd_data__v19;
        CData/*0:0*/ __VdlySet__tb_dx7_core__DOT__dut__DOT__env_cmd__v27;
        CData/*0:0*/ __VdlySet__tb_dx7_core__DOT__dut__DOT__env_cmd_data__v20;
        CData/*0:0*/ __VdlySet__tb_dx7_core__DOT__dut__DOT__env_cmd__v28;
        CData/*0:0*/ __VdlySet__tb_dx7_core__DOT__dut__DOT__env_cmd_data__v21;
        CData/*0:0*/ __VdlySet__tb_dx7_core__DOT__dut__DOT__env_cmd__v29;
        CData/*0:0*/ __VdlySet__tb_dx7_core__DOT__dut__DOT__env_cmd_data__v22;
        CData/*0:0*/ __VdlySet__tb_dx7_core__DOT__dut__DOT__env_cmd__v30;
        CData/*0:0*/ __VdlySet__tb_dx7_core__DOT__dut__DOT__env_cmd_data__v23;
        CData/*0:0*/ __VdlySet__tb_dx7_core__DOT__dut__DOT__env_cmd__v31;
        CData/*0:0*/ __VdlySet__tb_dx7_core__DOT__dut__DOT__env_cmd_data__v24;
        CData/*0:0*/ __VdlySet__tb_dx7_core__DOT__dut__DOT__n_pegdwn__v34;
        CData/*3:0*/ __VdlyDim0__tb_dx7_core__DOT__dut__DOT__n_pegtgt__v35;
        CData/*0:0*/ __VdlySet__tb_dx7_core__DOT__dut__DOT__n_pegtgt__v35;
        CData/*0:0*/ __VdlyVal__tb_dx7_core__DOT__dut__DOT__n_pegris__v35;
        CData/*3:0*/ __VdlyDim0__tb_dx7_core__DOT__dut__DOT__n_pegris__v35;
        CData/*0:0*/ __VdlySet__tb_dx7_core__DOT__dut__DOT__n_pegris__v35;
        CData/*3:0*/ __VdlyDim0__tb_dx7_core__DOT__dut__DOT__n_peginc__v35;
        CData/*0:0*/ __VdlySet__tb_dx7_core__DOT__dut__DOT__n_peginc__v35;
        CData/*7:0*/ __VdlyVal__tb_dx7_core__DOT__dut__DOT__n_seq__v16;
        CData/*3:0*/ __VdlyDim0__tb_dx7_core__DOT__dut__DOT__n_seq__v16;
        CData/*0:0*/ __VdlySet__tb_dx7_core__DOT__dut__DOT__n_seq__v16;
        CData/*6:0*/ __VdlyVal__tb_dx7_core__DOT__dut__DOT__n_midi__v16;
        CData/*3:0*/ __VdlyDim0__tb_dx7_core__DOT__dut__DOT__n_midi__v16;
        CData/*0:0*/ __VdlySet__tb_dx7_core__DOT__dut__DOT__n_midi__v16;
        CData/*3:0*/ __VdlyDim0__tb_dx7_core__DOT__dut__DOT__n_sil__v96;
        CData/*0:0*/ __VdlySet__tb_dx7_core__DOT__dut__DOT__n_sil__v96;
        CData/*0:0*/ __VdlySet__tb_dx7_core__DOT__dut__DOT__op_ph__v193;
        CData/*3:0*/ __VdlyDim1__tb_dx7_core__DOT__dut__DOT__op_go__v193;
        CData/*3:0*/ __VdlyDim1__tb_dx7_core__DOT__dut__DOT__op_go__v194;
        CData/*3:0*/ __VdlyDim1__tb_dx7_core__DOT__dut__DOT__op_go__v195;
        CData/*3:0*/ __VdlyDim1__tb_dx7_core__DOT__dut__DOT__op_go__v196;
        CData/*3:0*/ __VdlyDim1__tb_dx7_core__DOT__dut__DOT__op_go__v197;
        CData/*3:0*/ __VdlyDim1__tb_dx7_core__DOT__dut__DOT__op_go__v198;
        CData/*0:0*/ __VdlySet__tb_dx7_core__DOT__dut__DOT__op_ph__v199;
        CData/*3:0*/ __VdlyDim1__tb_dx7_core__DOT__dut__DOT__op_go__v199;
        CData/*3:0*/ __VdlyDim1__tb_dx7_core__DOT__dut__DOT__op_go__v200;
        CData/*3:0*/ __VdlyDim1__tb_dx7_core__DOT__dut__DOT__op_go__v201;
        CData/*3:0*/ __VdlyDim1__tb_dx7_core__DOT__dut__DOT__op_go__v202;
        CData/*3:0*/ __VdlyDim1__tb_dx7_core__DOT__dut__DOT__op_go__v203;
        CData/*3:0*/ __VdlyDim1__tb_dx7_core__DOT__dut__DOT__op_go__v204;
        CData/*3:0*/ __VdlyDim0__tb_dx7_core__DOT__dut__DOT__n_peglvl__v32;
        CData/*0:0*/ __VdlySet__tb_dx7_core__DOT__dut__DOT__n_peglvl__v32;
        CData/*3:0*/ __VdlyDim0__tb_dx7_core__DOT__dut__DOT__n_pegtgt__v36;
        CData/*0:0*/ __VdlySet__tb_dx7_core__DOT__dut__DOT__n_pegtgt__v36;
        CData/*0:0*/ __VdlyVal__tb_dx7_core__DOT__dut__DOT__n_pegris__v36;
        CData/*3:0*/ __VdlyDim0__tb_dx7_core__DOT__dut__DOT__n_pegris__v36;
        CData/*0:0*/ __VdlySet__tb_dx7_core__DOT__dut__DOT__n_pegris__v36;
        CData/*3:0*/ __VdlyDim0__tb_dx7_core__DOT__dut__DOT__n_peginc__v36;
        CData/*0:0*/ __VdlySet__tb_dx7_core__DOT__dut__DOT__n_peginc__v36;
        CData/*3:0*/ __VdlyDim0__tb_dx7_core__DOT__dut__DOT__n_pegtgt__v37;
        CData/*0:0*/ __VdlySet__tb_dx7_core__DOT__dut__DOT__n_pegtgt__v37;
        CData/*0:0*/ __VdlyVal__tb_dx7_core__DOT__dut__DOT__n_pegris__v37;
        CData/*3:0*/ __VdlyDim0__tb_dx7_core__DOT__dut__DOT__n_pegris__v37;
        CData/*0:0*/ __VdlySet__tb_dx7_core__DOT__dut__DOT__n_pegris__v37;
        CData/*3:0*/ __VdlyDim0__tb_dx7_core__DOT__dut__DOT__n_peginc__v37;
        CData/*0:0*/ __VdlySet__tb_dx7_core__DOT__dut__DOT__n_peginc__v37;
        CData/*0:0*/ __VdlySet__tb_dx7_core__DOT__dut__DOT__n_pegix__v36;
        CData/*0:0*/ __VdlySet__tb_dx7_core__DOT__dut__DOT__env_cmd__v32;
    };
    struct {
        CData/*0:0*/ __VdlySet__tb_dx7_core__DOT__dut__DOT__env_cmd_data__v25;
        CData/*0:0*/ __VdlySet__tb_dx7_core__DOT__dut__DOT__env_cmd__v33;
        CData/*0:0*/ __VdlySet__tb_dx7_core__DOT__dut__DOT__env_cmd_data__v26;
        CData/*0:0*/ __VdlySet__tb_dx7_core__DOT__dut__DOT__stg_dd__v0;
        CData/*0:0*/ __VdlySet__tb_dx7_core__DOT__dut__DOT__stg_dd__v1;
        CData/*0:0*/ __VdlySet__tb_dx7_core__DOT__dut__DOT__n_sil__v97;
        CData/*0:0*/ __VdlySet__tb_dx7_core__DOT__dut__DOT__op_ph__v206;
        CData/*0:0*/ __VdlySet__tb_dx7_core__DOT__dut__DOT__n_sil__v98;
        CData/*0:0*/ __VdlySet__tb_dx7_core__DOT__dut__DOT__n_sil__v99;
        CData/*0:0*/ __VdlySet__tb_dx7_core__DOT__dut__DOT__n_sil__v100;
        CData/*0:0*/ __VdlySet__tb_dx7_core__DOT__dut__DOT__n_sil__v101;
        CData/*0:0*/ __VdlySet__tb_dx7_core__DOT__dut__DOT__n_sil__v102;
        CData/*0:0*/ __VdlySet__tb_dx7_core__DOT__dut__DOT__n_sil__v103;
        CData/*0:0*/ __VdlySet__tb_dx7_core__DOT__dut__DOT__n_sil__v104;
        CData/*0:0*/ __VdlySet__tb_dx7_core__DOT__dut__DOT__n_sil__v105;
        CData/*0:0*/ __VdlySet__tb_dx7_core__DOT__dut__DOT__n_sil__v106;
        CData/*0:0*/ __VdlySet__tb_dx7_core__DOT__dut__DOT__n_sil__v107;
        CData/*0:0*/ __VdlySet__tb_dx7_core__DOT__dut__DOT__n_sil__v108;
        CData/*0:0*/ __VdlySet__tb_dx7_core__DOT__dut__DOT__n_sil__v109;
        CData/*0:0*/ __VdlySet__tb_dx7_core__DOT__dut__DOT__n_sil__v110;
        CData/*0:0*/ __VdlySet__tb_dx7_core__DOT__dut__DOT__n_sil__v111;
        CData/*0:0*/ __VdlySet__tb_dx7_core__DOT__dut__DOT__n_sil__v112;
        CData/*0:0*/ __VdlySet__tb_dx7_core__DOT__dut__DOT__cmt_opitch__v6;
        CData/*0:0*/ __VdlySet__tb_dx7_core__DOT__dut__DOT__cmt_opitch__v7;
        CData/*0:0*/ __VdlyDim1__tb_dx7_core__DOT__dut__DOT__mixbuf__v1217;
        CData/*0:0*/ __VdlySet__tb_dx7_core__DOT__dut__DOT__mixbuf__v1217;
        CData/*0:0*/ __VdlyDim1__tb_dx7_core__DOT__dut__DOT__mixbuf__v1218;
        CData/*0:0*/ __VdlyDim1__tb_dx7_core__DOT__dut__DOT__mixbuf__v1219;
        CData/*0:0*/ __VdlyDim1__tb_dx7_core__DOT__dut__DOT__mixbuf__v1220;
        CData/*0:0*/ __VdlyDim1__tb_dx7_core__DOT__dut__DOT__mixbuf__v1221;
        CData/*0:0*/ __VdlyDim1__tb_dx7_core__DOT__dut__DOT__mixbuf__v1222;
        CData/*0:0*/ __VdlyDim1__tb_dx7_core__DOT__dut__DOT__mixbuf__v1223;
        CData/*0:0*/ __VdlyDim1__tb_dx7_core__DOT__dut__DOT__mixbuf__v1224;
        CData/*0:0*/ __VdlyDim1__tb_dx7_core__DOT__dut__DOT__mixbuf__v1225;
        CData/*0:0*/ __VdlyDim1__tb_dx7_core__DOT__dut__DOT__mixbuf__v1226;
        CData/*0:0*/ __VdlyDim1__tb_dx7_core__DOT__dut__DOT__mixbuf__v1227;
        CData/*0:0*/ __VdlyDim1__tb_dx7_core__DOT__dut__DOT__mixbuf__v1228;
        CData/*0:0*/ __VdlyDim1__tb_dx7_core__DOT__dut__DOT__mixbuf__v1229;
        CData/*0:0*/ __VdlyDim1__tb_dx7_core__DOT__dut__DOT__mixbuf__v1230;
        CData/*0:0*/ __VdlyDim1__tb_dx7_core__DOT__dut__DOT__mixbuf__v1231;
        CData/*0:0*/ __VdlyDim1__tb_dx7_core__DOT__dut__DOT__mixbuf__v1232;
        CData/*0:0*/ __VdlyDim1__tb_dx7_core__DOT__dut__DOT__mixbuf__v1233;
        CData/*0:0*/ __VdlyDim1__tb_dx7_core__DOT__dut__DOT__mixbuf__v1234;
        CData/*0:0*/ __VdlyDim1__tb_dx7_core__DOT__dut__DOT__mixbuf__v1235;
        CData/*0:0*/ __VdlyDim1__tb_dx7_core__DOT__dut__DOT__mixbuf__v1236;
        CData/*0:0*/ __VdlyDim1__tb_dx7_core__DOT__dut__DOT__mixbuf__v1237;
        CData/*0:0*/ __VdlyDim1__tb_dx7_core__DOT__dut__DOT__mixbuf__v1238;
        CData/*0:0*/ __VdlyDim1__tb_dx7_core__DOT__dut__DOT__mixbuf__v1239;
        CData/*0:0*/ __VdlyDim1__tb_dx7_core__DOT__dut__DOT__mixbuf__v1240;
        CData/*0:0*/ __VdlyDim1__tb_dx7_core__DOT__dut__DOT__mixbuf__v1241;
        CData/*0:0*/ __VdlyDim1__tb_dx7_core__DOT__dut__DOT__mixbuf__v1242;
        CData/*0:0*/ __VdlyDim1__tb_dx7_core__DOT__dut__DOT__mixbuf__v1243;
        CData/*0:0*/ __VdlyDim1__tb_dx7_core__DOT__dut__DOT__mixbuf__v1244;
        CData/*0:0*/ __VdlyDim1__tb_dx7_core__DOT__dut__DOT__mixbuf__v1245;
        CData/*0:0*/ __VdlyDim1__tb_dx7_core__DOT__dut__DOT__mixbuf__v1246;
        CData/*0:0*/ __VdlyDim1__tb_dx7_core__DOT__dut__DOT__mixbuf__v1247;
        CData/*0:0*/ __VdlyDim1__tb_dx7_core__DOT__dut__DOT__mixbuf__v1248;
        CData/*0:0*/ __VdlyDim1__tb_dx7_core__DOT__dut__DOT__mixbuf__v1249;
        CData/*0:0*/ __VdlyDim1__tb_dx7_core__DOT__dut__DOT__mixbuf__v1250;
        CData/*0:0*/ __VdlyDim1__tb_dx7_core__DOT__dut__DOT__mixbuf__v1251;
        CData/*0:0*/ __VdlyDim1__tb_dx7_core__DOT__dut__DOT__mixbuf__v1252;
        CData/*0:0*/ __VdlyDim1__tb_dx7_core__DOT__dut__DOT__mixbuf__v1253;
        CData/*0:0*/ __VdlyDim1__tb_dx7_core__DOT__dut__DOT__mixbuf__v1254;
        CData/*0:0*/ __VdlyDim1__tb_dx7_core__DOT__dut__DOT__mixbuf__v1255;
    };
    struct {
        CData/*0:0*/ __VdlyDim1__tb_dx7_core__DOT__dut__DOT__mixbuf__v1256;
        CData/*0:0*/ __VdlyDim1__tb_dx7_core__DOT__dut__DOT__mixbuf__v1257;
        CData/*0:0*/ __VdlyDim1__tb_dx7_core__DOT__dut__DOT__mixbuf__v1258;
        CData/*0:0*/ __VdlyDim1__tb_dx7_core__DOT__dut__DOT__mixbuf__v1259;
        CData/*0:0*/ __VdlyDim1__tb_dx7_core__DOT__dut__DOT__mixbuf__v1260;
        CData/*0:0*/ __VdlyDim1__tb_dx7_core__DOT__dut__DOT__mixbuf__v1261;
        CData/*0:0*/ __VdlyDim1__tb_dx7_core__DOT__dut__DOT__mixbuf__v1262;
        CData/*0:0*/ __VdlyDim1__tb_dx7_core__DOT__dut__DOT__mixbuf__v1263;
        CData/*0:0*/ __VdlyDim1__tb_dx7_core__DOT__dut__DOT__mixbuf__v1264;
        CData/*0:0*/ __VdlyDim1__tb_dx7_core__DOT__dut__DOT__mixbuf__v1265;
        CData/*0:0*/ __VdlyDim1__tb_dx7_core__DOT__dut__DOT__mixbuf__v1266;
        CData/*0:0*/ __VdlyDim1__tb_dx7_core__DOT__dut__DOT__mixbuf__v1267;
        CData/*0:0*/ __VdlyDim1__tb_dx7_core__DOT__dut__DOT__mixbuf__v1268;
        CData/*0:0*/ __VdlyDim1__tb_dx7_core__DOT__dut__DOT__mixbuf__v1269;
        CData/*0:0*/ __VdlyDim1__tb_dx7_core__DOT__dut__DOT__mixbuf__v1270;
        CData/*0:0*/ __VdlyDim1__tb_dx7_core__DOT__dut__DOT__mixbuf__v1271;
        CData/*0:0*/ __VdlyDim1__tb_dx7_core__DOT__dut__DOT__mixbuf__v1272;
        CData/*0:0*/ __VdlyDim1__tb_dx7_core__DOT__dut__DOT__mixbuf__v1273;
        CData/*0:0*/ __VdlyDim1__tb_dx7_core__DOT__dut__DOT__mixbuf__v1274;
        CData/*0:0*/ __VdlyDim1__tb_dx7_core__DOT__dut__DOT__mixbuf__v1275;
        CData/*0:0*/ __VdlyDim1__tb_dx7_core__DOT__dut__DOT__mixbuf__v1276;
        CData/*0:0*/ __VdlyDim1__tb_dx7_core__DOT__dut__DOT__mixbuf__v1277;
        CData/*0:0*/ __VdlyDim1__tb_dx7_core__DOT__dut__DOT__mixbuf__v1278;
        CData/*0:0*/ __VdlyDim1__tb_dx7_core__DOT__dut__DOT__mixbuf__v1279;
        CData/*0:0*/ __VdlyDim1__tb_dx7_core__DOT__dut__DOT__mixbuf__v1280;
        CData/*0:0*/ __Vtrigprevexpr___TOP__tb_dx7_core__DOT__clk__0;
        SData/*8:0*/ tb_dx7_core__DOT__dut__DOT__sample_clk;
        SData/*15:0*/ tb_dx7_core__DOT__dut__DOT__frame_ctr;
        SData/*8:0*/ tb_dx7_core__DOT__dut__DOT__evq_cnt;
        SData/*15:0*/ tb_dx7_core__DOT__dut__DOT__n_live;
        SData/*15:0*/ tb_dx7_core__DOT__dut__DOT__n_keydown;
        SData/*15:0*/ tb_dx7_core__DOT__dut__DOT__n_sustained;
        SData/*15:0*/ tb_dx7_core__DOT__dut__DOT__n_reclaimed;
        SData/*15:0*/ tb_dx7_core__DOT__dut__DOT__n_used;
        SData/*15:0*/ tb_dx7_core__DOT__dut__DOT__n_silnow;
        SData/*15:0*/ tb_dx7_core__DOT__dut__DOT__l_sr1;
        SData/*15:0*/ tb_dx7_core__DOT__dut__DOT__l_a1;
        SData/*8:0*/ tb_dx7_core__DOT__dut__DOT__fq_fsh_s;
        SData/*15:0*/ tb_dx7_core__DOT__dut__DOT__r_ld_gain_out;
        SData/*9:0*/ tb_dx7_core__DOT__dut__DOT__w_fa;
        SData/*13:0*/ tb_dx7_core__DOT__dut__DOT__w_fl;
        SData/*8:0*/ tb_dx7_core__DOT__dut__DOT__w_fsh;
        SData/*12:0*/ tb_dx7_core__DOT__dut__DOT__dv_outlevel;
        SData/*15:0*/ tb_dx7_core__DOT__dut__DOT__note_silent;
        SData/*15:0*/ tb_dx7_core__DOT__dut__DOT__in_rel;
        SData/*9:0*/ tb_dx7_core__DOT__dut__DOT__u_router__DOT__w_dgain_q;
        SData/*15:0*/ tb_dx7_core__DOT__dut__DOT__u_router__DOT__g1_w;
        SData/*15:0*/ tb_dx7_core__DOT__dut__DOT__u_router__DOT__g2_w;
        SData/*15:0*/ tb_dx7_core__DOT__dut__DOT__u_router__DOT__dg1_w;
        SData/*15:0*/ tb_dx7_core__DOT__dut__DOT__u_router__DOT__dg2_w;
        SData/*14:0*/ tb_dx7_core__DOT__dut__DOT__u_router__DOT__og1_q;
        SData/*14:0*/ tb_dx7_core__DOT__dut__DOT__u_router__DOT__og2_q;
        SData/*14:0*/ tb_dx7_core__DOT__dut__DOT__u_router__DOT__gain1;
        SData/*14:0*/ tb_dx7_core__DOT__dut__DOT__u_router__DOT__gain2;
        SData/*14:0*/ tb_dx7_core__DOT__dut__DOT__u_router__DOT__og1;
        SData/*14:0*/ tb_dx7_core__DOT__dut__DOT__u_router__DOT__og2;
        SData/*15:0*/ tb_dx7_core__DOT__dut__DOT__u_router__DOT__sg1;
        SData/*15:0*/ tb_dx7_core__DOT__dut__DOT__u_router__DOT__sg2;
        SData/*15:0*/ tb_dx7_core__DOT__dut__DOT__u_router__DOT__gain_adv1;
        SData/*15:0*/ tb_dx7_core__DOT__dut__DOT__u_router__DOT__gain_adv2;
        SData/*15:0*/ __Vfunc_tb_dx7_core__DOT__dut__DOT__sil_op__188__go;
        SData/*10:0*/ __VdfgRegularize_hebeb780c_0_24;
        SData/*15:0*/ __Vdly__tb_dx7_core__DOT__dut__DOT__frame_ctr;
        SData/*8:0*/ __Vdly__tb_dx7_core__DOT__dut__DOT__evq_cnt;
    };
    struct {
        SData/*15:0*/ __Vdly__tb_dx7_core__DOT__dut__DOT__n_live;
        SData/*15:0*/ __Vdly__tb_dx7_core__DOT__dut__DOT__n_keydown;
        SData/*15:0*/ __Vdly__tb_dx7_core__DOT__dut__DOT__n_sustained;
        SData/*15:0*/ __Vdly__tb_dx7_core__DOT__dut__DOT__n_used;
        SData/*9:0*/ __Vdly__tb_dx7_core__DOT__dut__DOT__w_fa;
        SData/*13:0*/ __Vdly__tb_dx7_core__DOT__dut__DOT__w_fl;
        SData/*8:0*/ __Vdly__tb_dx7_core__DOT__dut__DOT__w_fsh;
        SData/*15:0*/ __VdlyVal__tb_dx7_core__DOT__dut__DOT__op_go__v96;
        IData/*31:0*/ tb_dx7_core__DOT____VlemCall_10__dec_at;
        IData/*31:0*/ tb_dx7_core__DOT____VlemCall_9__ndig;
        IData/*31:0*/ tb_dx7_core__DOT____VlemCall_8__dec_at;
        IData/*31:0*/ tb_dx7_core__DOT____VlemCall_7__ndig;
        IData/*31:0*/ tb_dx7_core__DOT____VlemCall_6__ndig;
        IData/*31:0*/ tb_dx7_core__DOT____VlemCall_5__dec_at;
        IData/*31:0*/ tb_dx7_core__DOT____VlemCall_4__ndig;
        IData/*31:0*/ tb_dx7_core__DOT__bit_i;
        IData/*31:0*/ tb_dx7_core__DOT__afd;
        VlWide<32>/*1023:0*/ tb_dx7_core__DOT__vfile;
        VlWide<32>/*1023:0*/ tb_dx7_core__DOT__afile;
        VlWide<32>/*1023:0*/ tb_dx7_core__DOT__mfile;
        VlWide<8>/*255:0*/ tb_dx7_core__DOT__line;
        IData/*31:0*/ tb_dx7_core__DOT__rc;
        IData/*31:0*/ tb_dx7_core__DOT__p0;
        IData/*31:0*/ tb_dx7_core__DOT__pd;
        IData/*31:0*/ tb_dx7_core__DOT__vdec;
        IData/*31:0*/ tb_dx7_core__DOT__addr;
        IData/*31:0*/ tb_dx7_core__DOT__data;
        IData/*31:0*/ tb_dx7_core__DOT__block;
        IData/*31:0*/ tb_dx7_core__DOT__samples;
        IData/*31:0*/ tb_dx7_core__DOT__wait_frames__Vstatic__n;
        IData/*31:0*/ tb_dx7_core__DOT__wait_frames__Vstatic__k;
        IData/*31:0*/ tb_dx7_core__DOT__wait_until__Vstatic__fr;
        IData/*31:0*/ tb_dx7_core__DOT__wait_until_samples__Vstatic__target;
        IData/*31:0*/ tb_dx7_core__DOT__chex__Vstatic__k;
        IData/*31:0*/ tb_dx7_core__DOT__dec_at__Vstatic__k;
        IData/*31:0*/ tb_dx7_core__DOT__dec_at__Vstatic__v;
        IData/*31:0*/ tb_dx7_core__DOT__dec_at__Vstatic__c;
        IData/*31:0*/ tb_dx7_core__DOT__ndig__Vstatic__k;
        IData/*31:0*/ tb_dx7_core__DOT__ndig__Vstatic__c;
        IData/*22:0*/ tb_dx7_core__DOT__tap_q;
        IData/*31:0*/ tb_dx7_core__DOT__dut__DOT____VlemCall_30__peg_rate_inc;
        IData/*31:0*/ tb_dx7_core__DOT__dut__DOT____VlemCall_29__peg_tab19;
        IData/*31:0*/ tb_dx7_core__DOT__dut__DOT____VlemCall_28__peg_tab19;
        IData/*31:0*/ tb_dx7_core__DOT__dut__DOT____VlemCall_27__peg_rate_inc;
        IData/*31:0*/ tb_dx7_core__DOT__dut__DOT____VlemCall_26__peg_tab19;
        IData/*31:0*/ tb_dx7_core__DOT__dut__DOT____VlemCall_25__peg_tab19;
        IData/*31:0*/ tb_dx7_core__DOT__dut__DOT____VlemCall_24__peg_rate_inc;
        IData/*31:0*/ tb_dx7_core__DOT__dut__DOT____VlemCall_23__peg_tab19;
        IData/*31:0*/ tb_dx7_core__DOT__dut__DOT____VlemCall_22__peg_tab19;
        IData/*31:0*/ tb_dx7_core__DOT__dut__DOT____VlemCall_21__peg_rate_inc;
        IData/*31:0*/ tb_dx7_core__DOT__dut__DOT____VlemCall_20__peg_tab19;
        IData/*31:0*/ tb_dx7_core__DOT__dut__DOT____VlemCall_19__peg_tab19;
        IData/*31:0*/ tb_dx7_core__DOT__dut__DOT____VlemCall_18__peg_rate_inc;
        IData/*31:0*/ tb_dx7_core__DOT__dut__DOT____VlemCall_17__peg_tab19;
        IData/*31:0*/ tb_dx7_core__DOT__dut__DOT____VlemCall_16__peg_tab19;
        IData/*31:0*/ tb_dx7_core__DOT__dut__DOT____VlemCall_15__peg_rate_inc;
        IData/*31:0*/ tb_dx7_core__DOT__dut__DOT____VlemCall_14__peg_tab19;
        IData/*31:0*/ tb_dx7_core__DOT__dut__DOT____VlemCall_13__peg_tab19;
        IData/*31:0*/ tb_dx7_core__DOT__dut__DOT____VlemCall_12__peg_tab19;
        IData/*31:0*/ tb_dx7_core__DOT__dut__DOT____VlemCall_11__peg_tab19;
        IData/*24:0*/ tb_dx7_core__DOT__dut__DOT____VlemCall_10__ampsens_tab;
        IData/*24:0*/ tb_dx7_core__DOT__dut__DOT____VlemCall_9__ampsens_tab;
        IData/*24:0*/ tb_dx7_core__DOT__dut__DOT____VlemCall_8__ampsens_tab;
        IData/*24:0*/ tb_dx7_core__DOT__dut__DOT____VlemCall_7__ampsens_tab;
    };
    struct {
        IData/*24:0*/ tb_dx7_core__DOT__dut__DOT____VlemCall_6__ampsens_tab;
        IData/*24:0*/ tb_dx7_core__DOT__dut__DOT____VlemCall_5__ampsens_tab;
        IData/*31:0*/ tb_dx7_core__DOT__dut__DOT__shd_globA;
        IData/*31:0*/ tb_dx7_core__DOT__dut__DOT__shd_globB;
        IData/*31:0*/ tb_dx7_core__DOT__dut__DOT__shd_globC;
        IData/*31:0*/ tb_dx7_core__DOT__dut__DOT__shd_pegr;
        IData/*31:0*/ tb_dx7_core__DOT__dut__DOT__shd_pegl;
        IData/*31:0*/ tb_dx7_core__DOT__dut__DOT__cmt_globA;
        IData/*31:0*/ tb_dx7_core__DOT__dut__DOT__cmt_globB;
        IData/*31:0*/ tb_dx7_core__DOT__dut__DOT__cmt_globC;
        IData/*31:0*/ tb_dx7_core__DOT__dut__DOT__cmt_pegr;
        IData/*31:0*/ tb_dx7_core__DOT__dut__DOT__cmt_pegl;
        IData/*31:0*/ tb_dx7_core__DOT__dut__DOT__bend_pb;
        IData/*31:0*/ tb_dx7_core__DOT__dut__DOT__master_tune;
        IData/*31:0*/ tb_dx7_core__DOT__dut__DOT__ctrl_pm;
        IData/*31:0*/ tb_dx7_core__DOT__dut__DOT__ctrl_am;
        IData/*31:0*/ tb_dx7_core__DOT__dut__DOT__eg_mod;
        VlWide<3>/*95:0*/ tb_dx7_core__DOT__dut__DOT__env_busy;
        VlWide<3>/*95:0*/ tb_dx7_core__DOT__dut__DOT__env_cmd_en;
        IData/*31:0*/ tb_dx7_core__DOT__dut__DOT__lfo_phase;
        IData/*31:0*/ tb_dx7_core__DOT__dut__DOT__lfo_delta;
        IData/*31:0*/ tb_dx7_core__DOT__dut__DOT__lfo_dstate;
        IData/*31:0*/ tb_dx7_core__DOT__dut__DOT__lfo_dinc1;
        IData/*31:0*/ tb_dx7_core__DOT__dut__DOT__lfo_dinc2;
        IData/*24:0*/ tb_dx7_core__DOT__dut__DOT__lfo_val_q;
        IData/*24:0*/ tb_dx7_core__DOT__dut__DOT__lfo_del_q;
        IData/*31:0*/ tb_dx7_core__DOT__dut__DOT__l_ph_n;
        IData/*24:0*/ tb_dx7_core__DOT__dut__DOT__exp_amd;
        IData/*24:0*/ tb_dx7_core__DOT__dut__DOT__exp_ams;
        IData/*25:0*/ tb_dx7_core__DOT__dut__DOT__exp_y;
        VlWide<3>/*79:0*/ tb_dx7_core__DOT__dut__DOT__exp_t1;
        VlWide<3>/*65:0*/ tb_dx7_core__DOT__dut__DOT__exp_arg;
        VlWide<3>/*66:0*/ tb_dx7_core__DOT__dut__DOT__exp_zq;
        IData/*31:0*/ tb_dx7_core__DOT__dut__DOT__exp_pt_q;
        IData/*24:0*/ tb_dx7_core__DOT__dut__DOT__exp_x;
        IData/*31:0*/ tb_dx7_core__DOT__dut__DOT__pm_nobase_w;
        IData/*31:0*/ tb_dx7_core__DOT__dut__DOT__pbase_w;
        IData/*31:0*/ tb_dx7_core__DOT__dut__DOT__amd_w;
        IData/*31:0*/ tb_dx7_core__DOT__dut__DOT__w_peg;
        IData/*31:0*/ tb_dx7_core__DOT__dut__DOT__fq_sel;
        IData/*31:0*/ tb_dx7_core__DOT__dut__DOT__r_cfg_fb0;
        IData/*31:0*/ tb_dx7_core__DOT__dut__DOT__r_cfg_fb1;
        IData/*31:0*/ tb_dx7_core__DOT__dut__DOT__r_ld_phase;
        IData/*31:0*/ tb_dx7_core__DOT__dut__DOT__r_ld_freq;
        IData/*27:0*/ tb_dx7_core__DOT__dut__DOT__r_ld_level;
        IData/*31:0*/ tb_dx7_core__DOT__dut__DOT__w_level;
        IData/*31:0*/ tb_dx7_core__DOT__dut__DOT__w_li;
        IData/*31:0*/ tb_dx7_core__DOT__dut__DOT__dv_erates;
        IData/*31:0*/ tb_dx7_core__DOT__dut__DOT__dv_elevels;
        IData/*31:0*/ tb_dx7_core__DOT__dut__DOT__dv_scaleA;
        IData/*31:0*/ tb_dx7_core__DOT__dut__DOT__dv_scaleB;
        IData/*31:0*/ tb_dx7_core__DOT__dut__DOT__dv_bpf0;
        IData/*31:0*/ tb_dx7_core__DOT__dut__DOT__dv_bpr1;
        IData/*31:0*/ tb_dx7_core__DOT__dut__DOT__t_peg_up;
        IData/*31:0*/ tb_dx7_core__DOT__dut__DOT__t_peg_dn;
        IData/*31:0*/ tb_dx7_core__DOT__dut__DOT__t_peg_nxt;
        IData/*31:0*/ tb_dx7_core__DOT__dut__DOT__w_pmax;
        IData/*31:0*/ tb_dx7_core__DOT__dut__DOT__w_am1b;
        IData/*31:0*/ tb_dx7_core__DOT__dut__DOT__w_am2;
        IData/*31:0*/ tb_dx7_core__DOT__dut__DOT__w_amax;
        IData/*31:0*/ tb_dx7_core__DOT__dut__DOT__w_ambase;
        IData/*31:0*/ tb_dx7_core__DOT__dut__DOT__ar_eval_y;
        IData/*31:0*/ tb_dx7_core__DOT__dut__DOT__ar_rd_data;
        IData/*23:0*/ tb_dx7_core__DOT__dut__DOT__i2s_sh;
    };
    struct {
        IData/*31:0*/ tb_dx7_core__DOT__dut__DOT__mixbuf_obs0;
        IData/*31:0*/ tb_dx7_core__DOT__dut__DOT__mixbuf_obs1;
        IData/*31:0*/ tb_dx7_core__DOT__dut__DOT__u_router__DOT__fb0_q;
        IData/*31:0*/ tb_dx7_core__DOT__dut__DOT__u_router__DOT__fb1_q;
        IData/*31:0*/ tb_dx7_core__DOT__dut__DOT__u_router__DOT__y0_w;
        IData/*31:0*/ tb_dx7_core__DOT__dut__DOT__u_router__DOT__y1_w;
        IData/*31:0*/ tb_dx7_core__DOT__dut__DOT__u_router__DOT__w_ph;
        IData/*31:0*/ tb_dx7_core__DOT__dut__DOT__u_router__DOT__s_ph1;
        IData/*31:0*/ tb_dx7_core__DOT__dut__DOT__u_router__DOT__s_ph2;
        IData/*16:0*/ tb_dx7_core__DOT__dut__DOT__u_router__DOT__w_gain;
        IData/*31:0*/ tb_dx7_core__DOT__dut__DOT__u_router__DOT__y_mid1;
        IData/*31:0*/ tb_dx7_core__DOT__dut__DOT__u_router__DOT__y_mid2;
        IData/*31:0*/ tb_dx7_core__DOT__dut__DOT__u_router__DOT__eval_mod_r;
        IData/*16:0*/ tb_dx7_core__DOT__dut__DOT__u_router__DOT__gain_adv;
        VlWide<5>/*132:0*/ __Vfunc_tb_dx7_core__DOT__dut__DOT__sil_op__188__s;
        IData/*31:0*/ __VdfgRegularize_hebeb780c_0_2;
        IData/*25:0*/ __Vdly__tb_dx7_core__DOT__dut__DOT__exp_y;
        VlWide<3>/*79:0*/ __Vdly__tb_dx7_core__DOT__dut__DOT__exp_t1;
        VlWide<3>/*65:0*/ __Vdly__tb_dx7_core__DOT__dut__DOT__exp_arg;
        VlWide<3>/*66:0*/ __Vdly__tb_dx7_core__DOT__dut__DOT__exp_zq;
        IData/*31:0*/ __Vdly__tb_dx7_core__DOT__dut__DOT__bend_pb;
        IData/*31:0*/ __Vdly__tb_dx7_core__DOT__dut__DOT__master_tune;
        IData/*31:0*/ __Vdly__tb_dx7_core__DOT__dut__DOT__cmt_globA;
        IData/*31:0*/ __Vdly__tb_dx7_core__DOT__dut__DOT__cmt_globB;
        IData/*31:0*/ __Vdly__tb_dx7_core__DOT__dut__DOT__cmt_globC;
        IData/*31:0*/ __Vdly__tb_dx7_core__DOT__dut__DOT__cmt_pegr;
        IData/*31:0*/ __Vdly__tb_dx7_core__DOT__dut__DOT__cmt_pegl;
        IData/*31:0*/ __Vdly__tb_dx7_core__DOT__dut__DOT__pm_nobase_w;
        IData/*31:0*/ __Vdly__tb_dx7_core__DOT__dut__DOT__pbase_w;
        IData/*31:0*/ __Vdly__tb_dx7_core__DOT__dut__DOT__amd_w;
        IData/*31:0*/ __Vdly__tb_dx7_core__DOT__dut__DOT__w_peg;
        IData/*31:0*/ __Vdly__tb_dx7_core__DOT__dut__DOT__w_level;
        IData/*31:0*/ __Vdly__tb_dx7_core__DOT__dut__DOT__w_li;
        IData/*31:0*/ __Vdly__tb_dx7_core__DOT__dut__DOT__fq_sel;
        IData/*31:0*/ __VdlyVal__tb_dx7_core__DOT__dut__DOT__shd_opitch__v6;
        IData/*31:0*/ __VdlyVal__tb_dx7_core__DOT__dut__DOT__shd_fterm__v6;
        IData/*31:0*/ __VdlyVal__tb_dx7_core__DOT__dut__DOT__shd_erates__v6;
        IData/*31:0*/ __VdlyVal__tb_dx7_core__DOT__dut__DOT__shd_elevels__v6;
        IData/*31:0*/ __VdlyVal__tb_dx7_core__DOT__dut__DOT__shd_scaleA__v6;
        IData/*31:0*/ __VdlyVal__tb_dx7_core__DOT__dut__DOT__shd_scaleB__v6;
        IData/*31:0*/ __VdlyVal__tb_dx7_core__DOT__dut__DOT__n_pegtgt__v16;
        IData/*31:0*/ __VdlyVal__tb_dx7_core__DOT__dut__DOT__n_peginc__v16;
        IData/*31:0*/ __VdlyVal__tb_dx7_core__DOT__dut__DOT__n_pegtgt__v33;
        IData/*31:0*/ __VdlyVal__tb_dx7_core__DOT__dut__DOT__n_peginc__v33;
        IData/*31:0*/ __VdlyVal__tb_dx7_core__DOT__dut__DOT__n_pegtgt__v34;
        IData/*31:0*/ __VdlyVal__tb_dx7_core__DOT__dut__DOT__n_peginc__v34;
        IData/*31:0*/ __VdlyVal__tb_dx7_core__DOT__dut__DOT__n_pegtgt__v35;
        IData/*31:0*/ __VdlyVal__tb_dx7_core__DOT__dut__DOT__n_peginc__v35;
        IData/*31:0*/ __VdlyVal__tb_dx7_core__DOT__dut__DOT__n_peglvl__v32;
        IData/*31:0*/ __VdlyVal__tb_dx7_core__DOT__dut__DOT__n_pegtgt__v36;
        IData/*31:0*/ __VdlyVal__tb_dx7_core__DOT__dut__DOT__n_peginc__v36;
        IData/*31:0*/ __VdlyVal__tb_dx7_core__DOT__dut__DOT__n_pegtgt__v37;
        IData/*31:0*/ __VdlyVal__tb_dx7_core__DOT__dut__DOT__n_peginc__v37;
        IData/*31:0*/ __VdlyVal__tb_dx7_core__DOT__dut__DOT__cmt_opitch__v6;
        IData/*31:0*/ __VdlyVal__tb_dx7_core__DOT__dut__DOT__cmt_erates__v6;
        IData/*31:0*/ __VdlyVal__tb_dx7_core__DOT__dut__DOT__cmt_scaleA__v6;
        IData/*31:0*/ __VdlyVal__tb_dx7_core__DOT__dut__DOT__cmt_scaleB__v6;
        IData/*31:0*/ __VdlyVal__tb_dx7_core__DOT__dut__DOT__cmt_opitch__v7;
        IData/*31:0*/ __VdlyVal__tb_dx7_core__DOT__dut__DOT__cmt_erates__v7;
        IData/*31:0*/ __VdlyVal__tb_dx7_core__DOT__dut__DOT__cmt_scaleA__v7;
        IData/*31:0*/ __VdlyVal__tb_dx7_core__DOT__dut__DOT__cmt_scaleB__v7;
        IData/*31:0*/ __VdlyVal__tb_dx7_core__DOT__dut__DOT__cmt_opitch__v8;
        IData/*31:0*/ __VdlyVal__tb_dx7_core__DOT__dut__DOT__cmt_erates__v8;
        IData/*31:0*/ __VdlyVal__tb_dx7_core__DOT__dut__DOT__cmt_scaleA__v8;
    };
    struct {
        IData/*31:0*/ __VdlyVal__tb_dx7_core__DOT__dut__DOT__cmt_scaleB__v8;
        IData/*31:0*/ __VdlyVal__tb_dx7_core__DOT__dut__DOT__cmt_opitch__v9;
        IData/*31:0*/ __VdlyVal__tb_dx7_core__DOT__dut__DOT__cmt_erates__v9;
        IData/*31:0*/ __VdlyVal__tb_dx7_core__DOT__dut__DOT__cmt_scaleA__v9;
        IData/*31:0*/ __VdlyVal__tb_dx7_core__DOT__dut__DOT__cmt_scaleB__v9;
        IData/*31:0*/ __VdlyVal__tb_dx7_core__DOT__dut__DOT__cmt_opitch__v10;
        IData/*31:0*/ __VdlyVal__tb_dx7_core__DOT__dut__DOT__cmt_erates__v10;
        IData/*31:0*/ __VdlyVal__tb_dx7_core__DOT__dut__DOT__cmt_scaleA__v10;
        IData/*31:0*/ __VdlyVal__tb_dx7_core__DOT__dut__DOT__cmt_scaleB__v10;
        IData/*31:0*/ __VdlyVal__tb_dx7_core__DOT__dut__DOT__cmt_opitch__v11;
        IData/*31:0*/ __VdlyVal__tb_dx7_core__DOT__dut__DOT__cmt_erates__v11;
        IData/*31:0*/ __VdlyVal__tb_dx7_core__DOT__dut__DOT__cmt_scaleA__v11;
        IData/*31:0*/ __VdlyVal__tb_dx7_core__DOT__dut__DOT__cmt_scaleB__v11;
        IData/*31:0*/ __Vi;
        QData/*47:0*/ tb_dx7_core__DOT__tx_frame;
        QData/*47:0*/ tb_dx7_core__DOT__spi_xfer__Vstatic__f;
        QData/*47:0*/ tb_dx7_core__DOT__dut__DOT__shift_in;
        QData/*47:0*/ tb_dx7_core__DOT__dut__DOT__frame_reg;
        QData/*47:0*/ tb_dx7_core__DOT__dut__DOT__frame_captured;
        QData/*36:0*/ tb_dx7_core__DOT__dut__DOT__evq_out;
        QData/*32:0*/ tb_dx7_core__DOT__dut__DOT__l_dsum;
        QData/*61:0*/ tb_dx7_core__DOT__dut__DOT__exp_T;
        QData/*56:0*/ tb_dx7_core__DOT__dut__DOT__exp_h;
        QData/*62:0*/ tb_dx7_core__DOT__dut__DOT__exp_res;
        QData/*56:0*/ tb_dx7_core__DOT__dut__DOT__exp_hn;
        QData/*39:0*/ tb_dx7_core__DOT__dut__DOT__w_sl0;
        QData/*61:0*/ __Vdly__tb_dx7_core__DOT__dut__DOT__exp_T;
        QData/*56:0*/ __Vdly__tb_dx7_core__DOT__dut__DOT__exp_h;
        QData/*62:0*/ __Vdly__tb_dx7_core__DOT__dut__DOT__exp_res;
        QData/*32:0*/ __VdlyVal__tb_dx7_core__DOT__dut__DOT__mixbuf__v1152;
        VlUnpacked<IData/*31:0*/, 16> tb_dx7_core__DOT__commit_list;
        VlUnpacked<QData/*48:0*/, 8> tb_dx7_core__DOT__dut__DOT__skid;
        VlUnpacked<IData/*31:0*/, 6> tb_dx7_core__DOT__dut__DOT__shd_opitch;
        VlUnpacked<IData/*31:0*/, 6> tb_dx7_core__DOT__dut__DOT__shd_fterm;
        VlUnpacked<IData/*31:0*/, 6> tb_dx7_core__DOT__dut__DOT__shd_erates;
        VlUnpacked<IData/*31:0*/, 6> tb_dx7_core__DOT__dut__DOT__shd_elevels;
        VlUnpacked<IData/*31:0*/, 6> tb_dx7_core__DOT__dut__DOT__shd_scaleA;
        VlUnpacked<IData/*31:0*/, 6> tb_dx7_core__DOT__dut__DOT__shd_scaleB;
        VlUnpacked<QData/*36:0*/, 168> tb_dx7_core__DOT__dut__DOT__evq;
        VlUnpacked<IData/*31:0*/, 6> tb_dx7_core__DOT__dut__DOT__cmt_opitch;
        VlUnpacked<IData/*31:0*/, 6> tb_dx7_core__DOT__dut__DOT__cmt_fterm;
        VlUnpacked<IData/*31:0*/, 6> tb_dx7_core__DOT__dut__DOT__cmt_erates;
        VlUnpacked<IData/*31:0*/, 6> tb_dx7_core__DOT__dut__DOT__cmt_elevels;
        VlUnpacked<IData/*31:0*/, 6> tb_dx7_core__DOT__dut__DOT__cmt_scaleA;
        VlUnpacked<IData/*31:0*/, 6> tb_dx7_core__DOT__dut__DOT__cmt_scaleB;
        VlUnpacked<CData/*7:0*/, 6> tb_dx7_core__DOT__dut__DOT__c_mode;
        VlUnpacked<CData/*7:0*/, 6> tb_dx7_core__DOT__dut__DOT__c_coarse;
        VlUnpacked<CData/*7:0*/, 6> tb_dx7_core__DOT__dut__DOT__c_fine;
        VlUnpacked<CData/*7:0*/, 6> tb_dx7_core__DOT__dut__DOT__c_detune;
        VlUnpacked<CData/*6:0*/, 16> tb_dx7_core__DOT__dut__DOT__n_midi;
        VlUnpacked<CData/*6:0*/, 16> tb_dx7_core__DOT__dut__DOT__n_vel;
        VlUnpacked<CData/*7:0*/, 16> tb_dx7_core__DOT__dut__DOT__n_seq;
        VlUnpacked<CData/*6:0*/, 16> tb_dx7_core__DOT__dut__DOT__n_sil;
        VlUnpacked<VlUnpacked<IData/*31:0*/, 6>, 16> tb_dx7_core__DOT__dut__DOT__n_bp;
        VlUnpacked<CData/*5:0*/, 16> tb_dx7_core__DOT__dut__DOT__n_opmode;
        VlUnpacked<CData/*4:0*/, 16> tb_dx7_core__DOT__dut__DOT__n_alg;
        VlUnpacked<CData/*4:0*/, 16> tb_dx7_core__DOT__dut__DOT__n_fbs;
        VlUnpacked<CData/*7:0*/, 16> tb_dx7_core__DOT__dut__DOT__n_pmdep;
        VlUnpacked<CData/*7:0*/, 16> tb_dx7_core__DOT__dut__DOT__n_pmsens;
        VlUnpacked<CData/*7:0*/, 16> tb_dx7_core__DOT__dut__DOT__n_amdep;
        VlUnpacked<VlUnpacked<IData/*24:0*/, 6>, 16> tb_dx7_core__DOT__dut__DOT__n_ams;
        VlUnpacked<VlUnpacked<CData/*6:0*/, 4>, 16> tb_dx7_core__DOT__dut__DOT__n_pegr;
        VlUnpacked<VlUnpacked<CData/*6:0*/, 4>, 16> tb_dx7_core__DOT__dut__DOT__n_pegl;
        VlUnpacked<IData/*31:0*/, 16> tb_dx7_core__DOT__dut__DOT__n_peglvl;
    };
    struct {
        VlUnpacked<IData/*31:0*/, 16> tb_dx7_core__DOT__dut__DOT__n_pegtgt;
        VlUnpacked<IData/*31:0*/, 16> tb_dx7_core__DOT__dut__DOT__n_peginc;
        VlUnpacked<CData/*2:0*/, 16> tb_dx7_core__DOT__dut__DOT__n_pegix;
        VlUnpacked<CData/*0:0*/, 16> tb_dx7_core__DOT__dut__DOT__n_pegris;
        VlUnpacked<CData/*0:0*/, 16> tb_dx7_core__DOT__dut__DOT__n_pegdwn;
        VlUnpacked<IData/*31:0*/, 6> tb_dx7_core__DOT__dut__DOT__stg_dd;
        VlUnpacked<VlUnpacked<IData/*31:0*/, 6>, 16> tb_dx7_core__DOT__dut__DOT__op_ph;
        VlUnpacked<VlUnpacked<SData/*15:0*/, 6>, 16> tb_dx7_core__DOT__dut__DOT__op_go;
        VlUnpacked<VlUnpacked<IData/*31:0*/, 6>, 16> tb_dx7_core__DOT__dut__DOT__op_fq;
        VlUnpacked<VlUnpacked<IData/*31:0*/, 6>, 16> tb_dx7_core__DOT__dut__DOT__op_li;
        VlUnpacked<IData/*31:0*/, 16> tb_dx7_core__DOT__dut__DOT__n_fb0;
        VlUnpacked<IData/*31:0*/, 16> tb_dx7_core__DOT__dut__DOT__n_fb1;
        VlUnpacked<CData/*2:0*/, 96> tb_dx7_core__DOT__dut__DOT__env_cmd;
        VlUnpacked<VlWide<5>/*132:0*/, 96> tb_dx7_core__DOT__dut__DOT__env_cmd_data;
        VlUnpacked<VlWide<5>/*132:0*/, 96> tb_dx7_core__DOT__dut__DOT__env_rd;
        VlUnpacked<IData/*25:0*/, 2048> tb_dx7_core__DOT__dut__DOT__lfo_sin_rom;
        VlUnpacked<IData/*31:0*/, 1025> tb_dx7_core__DOT__dut__DOT__freqlut_rom;
        VlUnpacked<CData/*7:0*/, 16> tb_dx7_core__DOT__dut__DOT__age;
        VlUnpacked<VlUnpacked<QData/*32:0*/, 64>, 2> tb_dx7_core__DOT__dut__DOT__mixbuf;
        VlUnpacked<IData/*31:0*/, 6> tb_dx7_core__DOT__dut__DOT__u_router__DOT__phase_q;
        VlUnpacked<IData/*31:0*/, 6> tb_dx7_core__DOT__dut__DOT__u_router__DOT__freq_q;
        VlUnpacked<IData/*27:0*/, 6> tb_dx7_core__DOT__dut__DOT__u_router__DOT__level_q;
        VlUnpacked<SData/*15:0*/, 6> tb_dx7_core__DOT__dut__DOT__u_router__DOT__gaino_q;
        VlUnpacked<IData/*31:0*/, 64> tb_dx7_core__DOT__dut__DOT__u_router__DOT__bus1_q;
        VlUnpacked<IData/*31:0*/, 64> tb_dx7_core__DOT__dut__DOT__u_router__DOT__bus2_q;
        VlUnpacked<IData/*31:0*/, 64> tb_dx7_core__DOT__dut__DOT__u_router__DOT__nout_q;
        VlUnpacked<CData/*7:0*/, 192> tb_dx7_core__DOT__dut__DOT__u_router__DOT__alg_rom;
        VlUnpacked<SData/*15:0*/, 1024> tb_dx7_core__DOT__dut__DOT__u_kern__DOT__sinlog_rom;
        VlUnpacked<SData/*15:0*/, 1024> tb_dx7_core__DOT__dut__DOT__u_kern__DOT__sinexp_rom;
        VlUnpacked<QData/*63:0*/, 1> __VstlTriggered;
        VlUnpacked<QData/*63:0*/, 1> __VicoTriggered;
        VlUnpacked<QData/*63:0*/, 1> __VactTriggered;
        VlUnpacked<QData/*63:0*/, 1> __VactTriggeredAcc;
        VlUnpacked<QData/*63:0*/, 1> __VnbaTriggered;
    };
    VlDelayScheduler __VdlySched;
    VlTriggerScheduler __VtrigSched_h6456382b__0;

    // INTERNAL VARIABLES
    Vtb_dx7_core__Syms* vlSymsp;
    const char* vlNamep;

    // CONSTRUCTORS
    Vtb_dx7_core___024root(Vtb_dx7_core__Syms* symsp, const char* namep);
    ~Vtb_dx7_core___024root();
    VL_UNCOPYABLE(Vtb_dx7_core___024root);

    // INTERNAL METHODS
    void __Vconfigure(bool first);
};


#endif  // guard
