#!/usr/bin/env python3
"""Regenerate + SHA-256-pin the N02 operator tables (issue #16).

The gf180-parasynth table discipline (docs/REUSE-RULINGS.md,
gf180-parasynth gen_tables.py): a single generator produces the tables from
documented formulas, writes them as .hex plus a manifest pinning every
file's SHA-256, and --check re-runs the generation byte-for-byte so any
hand-edit or drift fails loudly. The generated bytes are the single source
of truth consumed by the Python model (src/gf180_dx7/model/tables.py
generates the identical bytes; the .hex + manifest are the committed pin).

Defaults: writes reference/tables/{sinlog_table,sinexp_table,freqlut_table}
.hex + manifest.json.

Exit codes: 0 PASS, 1 FAIL (drift), 2 usage error. Stdlib-only.
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
SRC = REPO_ROOT / "src"
if str(SRC) not in sys.path:
    sys.path.insert(0, str(SRC))

from gf180_dx7.model import tables  # noqa: E402

DEFAULT_OUT = REPO_ROOT / "reference" / "tables"


def main(argv=None) -> int:
    parser = argparse.ArgumentParser(
        description="Regenerate the pinned N02 operator tables")
    parser.add_argument("--out-dir", type=Path, default=DEFAULT_OUT,
                        help=f"output directory (default: {DEFAULT_OUT})")
    parser.add_argument("--check", action="store_true",
                        help="regenerate in memory and verify the committed "
                             "bytes + manifest without writing")
    parser.add_argument("--sample-rate", type=float, default=48000.0,
                        help="Freqlut sample rate (default: 48000)")
    args = parser.parse_args(argv)

    artifacts = tables.generate_all(args.sample_rate)

    if args.check:
        problems = []
        mpath = args.out_dir / tables.MANIFEST_NAME
        if not mpath.is_file():
            print(f"gen_tables: FAIL — missing {mpath}")
            return 1
        expected_text = __import__("json").dumps(
            tables.manifest(artifacts, args.sample_rate), indent=2,
            sort_keys=True) + "\n"
        actual_text = mpath.read_text(encoding="utf-8")
        if actual_text != expected_text:
            problems.append(f"{mpath}: manifest drifted (regeneration does "
                            "not match committed manifest)")
        for name, art in sorted(artifacts.items()):
            hpath = args.out_dir / (name + ".hex")
            if not hpath.is_file():
                problems.append(f"missing {hpath}")
                continue
            if hpath.read_text(encoding="ascii") != art.hex_text():
                problems.append(f"{hpath}: bytes drifted")
        if problems:
            for p in problems:
                print(f"gen_tables: FAIL — {p}")
            return 1
        print(f"gen_tables: PASS — {len(artifacts)} tables byte-identical, "
              f"manifest verified in {args.out_dir}")
        return 0

    tables.write_tables(args.out_dir, artifacts, args.sample_rate)
    for name, art in sorted(artifacts.items()):
        print(f"gen_tables: wrote {name}.hex "
              f"({art.entries} x {art.bits}-bit, sha256={art.sha256})")
    print(f"gen_tables: wrote {tables.MANIFEST_NAME} in {args.out_dir}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
