#!/usr/bin/env python3
"""H05 routing/feedback RTL conformance harness (issue #27).

The golden is the FROZEN PYTHON MODEL (src/gf180_dx7/model/algorithm.py,
contract gf180-dx7-integer-v1); the device under test is the RTL
(rtl/alg_router.v). The bar is bit-exactness -- no tolerance: any mismatch
means the RTL (or its table bytes) is wrong, never a loosened check.

Table artifact (parasynth gen_tables discipline, docs/REUSE-RULINGS.md):
`--gen-tables` regenerates reference/tables/alg_table.hex FROM the model's
ALGORITHMS table (fm_core.cc:29-62 facts) plus a manifest pinning its
SHA-256, so the Python model and the RTL's $readmemh share ONE table
artifact. `--check-tables` re-runs the generation in memory and fails on
any drift; every compare run performs the check before simulating, so a
mutated hex never silently becomes the shared artifact.

Conformance flow:
  1. build the directed run set from the model: ALL 32 algorithms x
     feedback {0, 3, 7} x 3 frames (scripted operator sources, block-level
     feedback recirculation across frames) plus directed fb-history-seed,
     fb-off-untouched and gating/has_contents runs (>= 6000 evals);
  2. drive rtl/tb_alg_router.v under iverilog; the bench streams the eval
     records (op, phase_in, gain, mod) and the per-frame note outputs and
     state readouts; the Python comparator judges bit-exact with
     first-mismatch localization (run, eval index, algorithm, op);
  3. NEGATIVE CONTROLS (issue #27): rebuild the RTL with
     -DH05_MUTATE_OP_ORDER (operator state addressing permuted; must fail
     on >= 28 of 32 algorithms), -DH05_INVERT_FB_SIGN (feedback term
     sign-flipped; every feedback>0 run must fail) and
     -DH05_DELAY_FB_COMMIT (history committed one block late; every
     feedback>0 run must fail) -- each mutant MUST fail the check it
     targets, proving the harness has resolution.

Exit codes: 0 pass, 1 check failure (clean-run mismatch, control not met,
or table drift), 2 could-not-run (missing iverilog/vvp; message names it).
Stdlib only.
"""

from __future__ import annotations

import argparse
import hashlib
import json
import os
import re
import shutil
import subprocess
import sys
import tempfile

REPO_ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SRC = os.path.join(REPO_ROOT, "src")
if SRC not in sys.path:
    sys.path.insert(0, SRC)

from gf180_dx7.model.algorithm import (  # noqa: E402
    ALGORITHMS, AlgorithmRouter, FmParams, decode_op, fb_shift_for)

RTL_REL = "rtl/alg_router.v"
TB_REL = "rtl/tb_alg_router.v"
OUTDIR_REL = "evidence/h05-routing-rtl"
HEX_REL = "reference/tables/alg_table.hex"
MANIFEST_REL = "reference/tables/alg_manifest.json"
MIN_EVALS = 6000

U32 = 0xFFFFFFFF

# Scripted source (the model's sin_fn seam): op k's output at global eval
# index t with modulation term m, wrapped to int32 like a real kernel.
BASE = [110 * (k + 1) for k in range(6)]
STEP = [7 * k + 3 for k in range(6)]
WMUL = 3

# Scenario constants mirroring tests/test_algorithm.py (N04 battery).
PARKED_LEVEL = 15360 << 14      # gain2 = ENV_MAX - 15360 = 1024
GATED_LEVEL = 16 << 16          # gain2 = 16320 > 16284 -> gate-skipped
FRAMES = 3

FB_SETTINGS = (0, 3, 7)


class CheckFailure(Exception):
    pass


class CouldNotRun(Exception):
    pass


def w32(v: int) -> int:
    v &= U32
    return v - (1 << 32) if v >= (1 << 31) else v


def sha256_file(path):
    h = hashlib.sha256()
    with open(path, "rb") as f:
        for chunk in iter(lambda: f.read(65536), b""):
            h.update(chunk)
    return h.hexdigest()


# ---------------------------------------------------------------------------
# The shared table artifact (generated; sha-pinned; model == RTL bytes)
# ---------------------------------------------------------------------------

def build_alg_hex() -> str:
    lines = [
        "// h05 algorithm connection table (issue #27)",
        "// GENERATED by tools/h05_compare.py --gen-tables from the FROZEN",
        "// model table src/gf180_dx7/model/algorithm.py ALGORITHMS",
        "// (fm_core.cc:29-62 facts) so the Python model and this RTL ROM",
        "// share ONE table artifact (parasynth gen_tables discipline).",
        "// 32 rows x 6 op descriptors, one byte per op, row-major op 0..5.",
        "// sha256 pinned in reference/tables/alg_manifest.json; verified",
        "// by --check-tables before every simulation. DO NOT hand-edit.",
    ]
    for row in ALGORITHMS:
        lines.append(" ".join("%02x" % f for f in row))
    return "\n".join(lines) + "\n"


def build_alg_manifest(hex_text: str) -> dict:
    return {
        "schema": "gf180-dx7/table-manifest-v1",
        "table": "alg_table",
        "entries": 192,
        "bits": 8,
        "generator": "tools/h05_compare.py --gen-tables",
        "source": "src/gf180_dx7/model/algorithm.py ALGORITHMS "
                  "(fm_core.cc:29-62 facts); regenerated, never copied "
                  "(NUM-001); parasynth gen_tables discipline",
        "issue": "https://github.com/2AMLogic/gf180-dx7/issues/27",
        "sha256": hashlib.sha256(hex_text.encode("ascii")).hexdigest(),
    }


def gen_tables(outdir: str) -> None:
    hex_text = build_alg_hex()
    hex_path = os.path.join(outdir, "alg_table.hex")
    with open(hex_path, "w", encoding="ascii") as f:
        f.write(hex_text)
    with open(os.path.join(outdir, "alg_manifest.json"), "w",
              encoding="utf-8") as f:
        json.dump(build_alg_manifest(hex_text), f, indent=2, sort_keys=True)
        f.write("\n")


def check_tables(repo_root: str | None = None, hex_path: str | None = None,
                 manifest_path: str | None = None) -> dict:
    """Regenerate in memory and verify the committed bytes + manifest pin.

    Raises CheckFailure on any drift (hand-edit, mutation, stale manifest).
    """
    root = repo_root or REPO_ROOT
    hp = hex_path or os.path.join(root, HEX_REL)
    mp = manifest_path or os.path.join(root, MANIFEST_REL)
    hex_text = build_alg_hex()
    if not os.path.isfile(hp):
        raise CheckFailure(f"missing generated table artifact: {hp}")
    with open(hp, "r", encoding="ascii") as f:
        committed = f.read()
    if committed != hex_text:
        raise CheckFailure(
            f"{hp}: bytes drifted from regeneration of "
            "src/gf180_dx7/model/algorithm.py ALGORITHMS (sha-pin check "
            "FAILED -- the model/RTL shared table artifact is corrupt)")
    if not os.path.isfile(mp):
        raise CheckFailure(f"missing table manifest: {mp}")
    with open(mp, "r", encoding="utf-8") as f:
        manifest = json.load(f)
    expected = build_alg_manifest(hex_text)
    if manifest != expected:
        raise CheckFailure(
            f"{mp}: manifest drifted from regeneration (sha-pin check "
            "FAILED)")
    return manifest


# ---------------------------------------------------------------------------
# Golden generation: drive the FROZEN model with the scripted source
# ---------------------------------------------------------------------------

def fb_op_index(alg: int) -> int:
    """The one feedback-loop op of a row ((flags & 0xC0) == 0xC0)."""
    for k in range(6):
        if decode_op(ALGORITHMS[alg][k])[3]:
            return k
    raise CheckFailure(f"algorithm {alg + 1} has no feedback op")


def scenarios():
    """The directed run set: (name, alg 0-based, feedback, per-op level_in,
    fb seed, fb_inert). Deterministic; the matrix is 32 x {0,3,7}.

    fb_inert marks runs whose feedback op is gate-skipped: no feedback
    path is exercised, so feedback-sign/delay mutants are provably
    invisible there and the mutant controls exclude them.
    """
    runs = []
    parked = [PARKED_LEVEL] * 6
    for alg in range(32):
        for fb in FB_SETTINGS:
            runs.append(("matrix", alg, fb, parked, (0, 0), False))
    # fb-history seeds: frame-start read path, depth-2 window, +2 shifts.
    seed = (0, 1 << 20)
    for alg in (0, 3, 5, 7, 27, 31):
        for fb in (3, 7):
            runs.append(("fb-seed", alg, fb, parked, seed, False))
    # fb off must leave the history untouched.
    for alg in (7, 31):
        runs.append(("fb-off-untouched", alg, 0, parked, (12345, -6789),
                     False))
    # gating / has_contents scenarios (N04's list) at feedback 7.
    gated_scenarios = [
        (0, (0,)),    # ALG 1: fb op gated; chain falls back to pure
        (6, (0, 1)),  # ALG 7: op2's bus-add forced off
        (15, (2,)),   # ALG 16: bus2 writer gated -> pure add onto bus1
        (3, (0,)),    # ALG 4: serial skipped, generic per-op path
        (5, (0,)),    # ALG 6: serial skipped, generic per-op path
        (31, (0,)),   # ALG 32: gated add carrier
    ]
    for alg, gated in gated_scenarios:
        levels = [GATED_LEVEL if k in gated else PARKED_LEVEL
                  for k in range(6)]
        runs.append(("gated", alg, 7, levels, (0, 0),
                     fb_op_index(alg) in set(gated)))
    return runs


def golden():
    """Run the FROZEN model over every scenario.

    Returns (program_lines, stream_lines, runs_meta, stats). stream_lines
    mirrors exactly what the bench emits: A markers, per-eval E records
    (op, phase_in, gain, mod), per-frame O (64 note outputs) and Q
    (6 phases, 6 gain_out, fb0, fb1) records.
    """
    program = [
        "# h05 routing/feedback directed program (issue #27)",
        "# generated by tools/h05_compare.py from the FROZEN model",
        "# src/gf180_dx7/model/algorithm.py "
        "(contract gf180-dx7-integer-v1)",
        "# table artifact: reference/tables/alg_table.hex "
        "(alg_manifest.json sha-pin)",
        "# A <alg hex2> <fb hex1>       new run (bench resets the DUT)",
        "# P <idx> <phase8> <freq8> <level8> <gain4>   load op params",
        "# F <fb0 hex8> <fb1 hex8>      load committed fb history",
        "# S                            render one 64-sample frame",
    ]
    stream = []
    meta = []
    total_evals = 0
    for idx, (kind, alg, fb, levels, fb_seed, fb_inert) in \
            enumerate(scenarios()):
        params = [FmParams() for _ in range(6)]
        for k, p in enumerate(params):
            p.freq = 1000 * (k + 1)
            p.level_in = levels[k]
        router = AlgorithmRouter(None, None)  # fresh buses per run
        fb_buf = list(fb_seed)
        calls = []

        def sin_fn(op, i, phase_plus, gain, mod):
            t = len(calls)
            m = w32(mod)
            y = w32(BASE[op] + t * STEP[op] + WMUL * m)
            calls.append((op, t, phase_plus & U32, gain & 0xFFFF,
                          m & U32, y & U32))
            return y

        shift = fb_shift_for(fb)
        program.append("A %02x %x" % (alg, fb))
        for k, p in enumerate(params):
            program.append("P %x %08x %08x %08x %04x"
                           % (k, p.phase & U32, p.freq & U32,
                              p.level_in & U32, p.gain_out & U32))
        program.append("F %08x %08x" % (fb_seed[0] & U32,
                                        fb_seed[1] & U32))
        stream.append("A %x %x" % (alg, fb))
        run_evals = 0
        for _frame in range(FRAMES):
            program.append("S")
            out = [0] * 64
            before = len(calls)
            router.render(out, params, alg, fb_buf, shift, sin_fn=sin_fn)
            for (op, _t, phase_in, gain, mod, _y) in calls[before:]:
                stream.append("E %x %08x %04x %08x"
                              % (op, phase_in, gain, mod))
            run_evals += len(calls) - before
            for v in out:
                stream.append("O %08x" % (v & U32))
            for p in params:
                stream.append("Q %08x" % (p.phase & U32))
            for p in params:
                stream.append("Q %08x" % (p.gain_out & U32))
            stream.append("Q %08x" % (fb_buf[0] & U32))
            stream.append("Q %08x" % (fb_buf[1] & U32))
        total_evals += run_evals
        meta.append({"run": idx, "kind": kind, "algorithm": alg + 1,
                     "feedback": fb, "frames": FRAMES, "evals": run_evals,
                     "fb_inert": fb_inert})
    stats = {
        "runs": len(meta),
        "matrix_runs": sum(1 for m in meta if m["kind"] == "matrix"),
        "directed_runs": sum(1 for m in meta if m["kind"] != "matrix"),
        "frames": sum(m["frames"] for m in meta),
        "evals": total_evals,
        "min_evals_required": MIN_EVALS,
        "algorithms": 32,
        "feedback_settings": list(FB_SETTINGS),
    }
    return program, stream, meta, stats


# ---------------------------------------------------------------------------
# Comparator: bit-exact with first-mismatch localization
# ---------------------------------------------------------------------------

def parse_stream(path):
    rows = []
    with open(path, "r", encoding="ascii") as f:
        for lineno, raw in enumerate(f, 1):
            line = raw.strip()
            if not line:
                continue
            rows.append((lineno, line.split()))
    return rows


def compare_streams(expected_rows, actual_rows, runs_meta):
    """Record-by-record bit-exact compare.

    Returns (mismatch_count, first_mismatch, per_run) where first_mismatch
    localizes (run index, algorithm, feedback, record kind, eval index, op).
    """
    first = None
    count = 0
    per_run = [{"status": "PASS", "mismatches": 0} for _ in runs_meta]
    run_of = []
    for i, m in enumerate(runs_meta):
        # stream records per run: 1 A marker + evals + frames*(64 O + 14 Q)
        run_of += [i] * (1 + m["evals"] + m["frames"] * (64 + 14))
    n = max(len(expected_rows), len(actual_rows))
    for k in range(n):
        if k >= len(expected_rows) or k >= len(actual_rows):
            count += 1
            if first is None:
                ridx = run_of[min(k, len(run_of) - 1)]
                m = runs_meta[ridx]
                first = {
                    "run": ridx, "algorithm": m["algorithm"],
                    "feedback": m["feedback"],
                    "error": "row-count mismatch: expected %d records, "
                             "RTL emitted %d" % (len(expected_rows),
                                                 len(actual_rows)),
                }
            break
        _, e = expected_rows[k]
        _, a = actual_rows[k]
        if e == a:
            continue
        count += 1
        ridx = run_of[k] if k < len(run_of) else -1
        if ridx >= 0:
            per_run[ridx]["status"] = "FAIL"
            per_run[ridx]["mismatches"] += 1
        if first is None:
            m = runs_meta[ridx] if ridx >= 0 else {}
            rec = {
                "line_expected": expected_rows[k][0],
                "line_actual": actual_rows[k][0],
                "expected": " ".join(e),
                "actual": " ".join(a),
                "run": ridx,
                "algorithm": m.get("algorithm"),
                "feedback": m.get("feedback"),
            }
            if e and a and e[0] == "E" == a[0]:
                rec["kind"] = "eval"
                # eval index within the run: E records since the run's
                # A marker on the expected side (the scripted source's t).
                idx = 0
                for j in range(k - 1, -1, -1):
                    tag = expected_rows[j][1][0]
                    if tag == "A":
                        break
                    if tag == "E":
                        idx += 1
                rec["eval_index"] = idx
                rec["op_expected"] = int(e[1], 16)
                rec["op_actual"] = int(a[1], 16)
            else:
                rec["kind"] = e[0] if e else "?"
            first = rec
    # a run whose record region shifted (a mutant that changes gating
    # changes the eval count) misaligns everything after the break; every
    # shifted record counts as a mismatch of the run that owns it, which
    # is the honest verdict for a structurally broken stream.
    return count, first, per_run


# ---------------------------------------------------------------------------
# simulation
# ---------------------------------------------------------------------------

MUTANTS = {
    "oporder": ("H05_MUTATE_OP_ORDER",
                "operator state addressing permuted 0..5 -> 5..0 "
                "(table row order unchanged, wrong operators gated/loaded)"),
    "fbsign": ("H05_INVERT_FB_SIGN",
               "feedback term sign inverted (mod = -scaled_fb)"),
    "fbdelay": ("H05_DELAY_FB_COMMIT",
                "fb history commit delayed one block (frame N reads "
                "frame N-2 results)"),
}


def tool_identity(iverilog):
    try:
        out = subprocess.run([iverilog, "-V"], capture_output=True,
                             text=True)
    except OSError:
        raise CouldNotRun(f"iverilog binary not found: {iverilog}")
    first = (out.stdout or out.stderr).strip().splitlines()
    if not first:
        raise CouldNotRun("iverilog -V produced no output")
    return first[0].strip()


def run_sim(iverilog, vvp, mutate, program_path, workdir):
    """Compile + run the bench; return path of the emitted stream file."""
    if shutil.which(iverilog) is None:
        raise CouldNotRun(f"iverilog not found on PATH: {iverilog}")
    if shutil.which(vvp) is None:
        raise CouldNotRun(f"vvp not found on PATH: {vvp}")
    vvp_out = os.path.join(workdir, "tb%s.vvp" % (("_" + mutate) if mutate
                                                  else ""))
    actual = os.path.join(workdir, "actual%s.txt" % (("_" + mutate) if
                                                     mutate else ""))
    cmd = [iverilog, "-g2012", "-o", vvp_out]
    if mutate:
        define = MUTANTS[mutate][0]
        cmd.append("-D" + define)
    cmd += [os.path.join(REPO_ROOT, RTL_REL), os.path.join(REPO_ROOT, TB_REL)]
    proc = subprocess.run(cmd, capture_output=True, text=True,
                          cwd=REPO_ROOT)
    if proc.returncode != 0:
        raise CheckFailure("iverilog compile failed: "
                           + (proc.stderr or proc.stdout)[-800:])
    try:
        run = subprocess.run([vvp, vvp_out, f"+program={program_path}",
                              f"+actual={actual}"],
                             capture_output=True, text=True, cwd=REPO_ROOT,
                             timeout=1800)
        out = run.stdout + run.stderr
        if run.returncode != 0 or "FAIL" in out:
            raise CheckFailure(f"bench failed: {out.strip()[-800:]}")
        m = re.search(r"PASS tb_alg_router \(runs=(\d+) frames=(\d+) "
                      r"evals=(\d+)\)", out)
        if not m:
            raise CheckFailure(f"bench produced no PASS summary: {out[-400:]}")
    finally:
        try:
            os.remove(vvp_out)
        except OSError:
            pass
    return actual, {
        "bench_runs": int(m.group(1)),
        "bench_frames": int(m.group(2)),
        "bench_evals": int(m.group(3)),
    }


# ---------------------------------------------------------------------------
# main
# ---------------------------------------------------------------------------

def main(argv=None):
    ap = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    ap.add_argument("--outdir", default=os.path.join(REPO_ROOT, OUTDIR_REL))
    ap.add_argument("--gen-tables", action="store_true",
                    help="regenerate the alg table hex + sha-pin manifest")
    ap.add_argument("--check-tables", action="store_true",
                    help="verify the committed table artifact only")
    ap.add_argument("--gen-only", action="store_true",
                    help="write program + gen report, no simulation")
    ap.add_argument("--skip-mutants", action="store_true",
                    help="run only the clean conformance build")
    ap.add_argument("--mutate-only", choices=sorted(MUTANTS), default=None,
                    help="run only one negative-control mutant build")
    ap.add_argument("--iverilog", default="iverilog")
    ap.add_argument("--vvp", default="vvp")
    args = ap.parse_args(argv)

    if args.gen_tables:
        gen_tables(os.path.dirname(os.path.join(REPO_ROOT, HEX_REL)))
        print("h05_compare: wrote %s + %s"
              % (HEX_REL, MANIFEST_REL))
        return 0
    if args.check_tables:
        try:
            manifest = check_tables()
        except CheckFailure as exc:
            print(f"FAIL: {exc}", file=sys.stderr)
            return 1
        print("h05_compare: table artifact byte-identical to the model "
              "(sha256 %s...)" % manifest["sha256"][:12])
        return 0

    try:
        manifest = check_tables()
    except CheckFailure as exc:
        print(f"FAIL: {exc}", file=sys.stderr)
        return 1

    try:
        program, stream, meta, stats = golden()
    except Exception as exc:
        print(f"COULD-NOT-RUN: golden generation failed: {exc}",
              file=sys.stderr)
        return 2
    if stats["evals"] < MIN_EVALS:
        print(f"FAIL: run set has {stats['evals']} evals < required "
              f"{MIN_EVALS}", file=sys.stderr)
        return 1

    os.makedirs(args.outdir, exist_ok=True)
    program_path = os.path.join(args.outdir, "program.txt")
    with open(program_path, "w", encoding="ascii") as f:
        f.write("\n".join(program) + "\n")

    if args.gen_only:
        report = {
            "schema": "h05-gen-report/1",
            "issue": 27,
            "planning_id": "H05",
            "golden": "src/gf180_dx7/model/algorithm.py "
                      "(gf180-dx7-integer-v1)",
            "table_artifact": {"hex": HEX_REL, "manifest": MANIFEST_REL,
                               "sha256": manifest["sha256"]},
            "stats": stats,
            "program_sha256": sha256_file(program_path),
            "stream_sha256": hashlib.sha256(
                "\n".join(stream).encode("ascii")).hexdigest(),
        }
        with open(os.path.join(args.outdir, "gen_report.json"), "w",
                  encoding="utf-8") as f:
            json.dump(report, f, indent=1, sort_keys=True)
            f.write("\n")
        print(f"h05_compare: generated {stats['runs']} runs "
              f"({stats['evals']} evals, {stats['frames']} frames) "
              f"-> {program_path}")
        return 0

    try:
        ident = tool_identity(args.iverilog)
    except CouldNotRun as exc:
        print(f"COULD-NOT-RUN: {exc}", file=sys.stderr)
        return 2

    expected_rows = parse_stream_expected(stream)
    report = {
        "schema": "h05-compare-report/1",
        "issue": 27,
        "planning_id": "H05",
        "claim_boundary": "RTL-vs-frozen-model bit-exactness of the "
                          "algorithm routing/feedback layer only; no "
                          "synthesis, timing, fit, or audibility claim; "
                          "operator kernel arithmetic is H01's scope",
        "tool_identity": {
            "iverilog": ident,
            "python": sys.version.split()[0],
            "rtl": {p: sha256_file(os.path.join(REPO_ROOT, p))
                    for p in (RTL_REL, TB_REL)},
            "table_artifact": {"hex": HEX_REL, "manifest": MANIFEST_REL,
                               "sha256": manifest["sha256"]},
        },
        "vector_stats": stats,
        "program_sha256": sha256_file(program_path),
        "stream_sha256": hashlib.sha256(
            "\n".join(stream).encode("ascii")).hexdigest(),
        "mutants": {},
    }

    status = "PASS"
    try:
        if not args.mutate_only:
            workdir = tempfile.mkdtemp(prefix="h05_sim_")
            try:
                actual_path, sim_meta = run_sim(
                    args.iverilog, args.vvp, None, program_path, workdir)
                actual_rows = parse_stream(actual_path)
            finally:
                shutil.rmtree(workdir, ignore_errors=True)
            count, first, per_run = compare_streams(expected_rows,
                                                    actual_rows, meta)
            failed_runs = sum(1 for r in per_run if r["status"] == "FAIL")
            matrix_fail = sum(
                1 for r, m in zip(per_run, meta)
                if r["status"] == "FAIL" and m["kind"] == "matrix")
            ok = (count == 0 and failed_runs == 0
                  and sim_meta["bench_evals"] == stats["evals"])
            report["conformance"] = dict(
                sim_meta,
                expected_records=len(expected_rows),
                actual_records=len(actual_rows),
                mismatch_records=count,
                failed_runs=failed_runs,
                failed_matrix_runs=matrix_fail,
                per_run=per_run,
                first_mismatch=first,
                status="PASS" if ok else "FAIL",
            )
            status = "PASS" if ok else "FAIL"

        if not args.skip_mutants and not args.mutate_only:
            for name in sorted(MUTANTS):
                res = run_mutant(args, name, program_path, expected_rows,
                                 meta, stats)
                report["mutants"][name] = res
                if not res["met"]:
                    status = "FAIL"

        if args.mutate_only:
            res = run_mutant(args, args.mutate_only, program_path,
                             expected_rows, meta, stats)
            report["mutants"][args.mutate_only] = res
            status = "PASS" if res["met"] else "FAIL"
    except CouldNotRun as exc:
        print(f"COULD-NOT-RUN: {exc}", file=sys.stderr)
        return 2
    except CheckFailure as exc:
        report["status"] = "FAIL"
        report["error"] = str(exc)
        with open(os.path.join(args.outdir, "compare_report.json"), "w",
                  encoding="utf-8") as f:
            json.dump(report, f, indent=1, sort_keys=True)
            f.write("\n")
        print(f"FAIL: {exc}", file=sys.stderr)
        return 1

    if args.skip_mutants:
        status = "PASS" if report["conformance"]["status"] == "PASS" \
            else "FAIL"
    report["status"] = status
    with open(os.path.join(args.outdir, "compare_report.json"), "w",
              encoding="utf-8") as f:
        json.dump(report, f, indent=1, sort_keys=True)
        f.write("\n")

    if "conformance" in report:
        cf = report["conformance"]
        print(f"conformance: {cf['status']} "
              f"({stats['runs']} runs / {stats['evals']} evals, "
              f"{cf['mismatch_records']} mismatching records, "
              f"{cf['failed_runs']} failing runs)")
        fm = cf["first_mismatch"]
        if fm:
            print("  first mismatch: run %s alg %s fb %s: expected %r "
                  "got %r" % (fm.get("run"), fm.get("algorithm"),
                              fm.get("feedback"), fm.get("expected"),
                              fm.get("actual")))
    for name, res in report["mutants"].items():
        print("negative control %s: %s" % (name, res["status"]))
    print(f"report: {os.path.join(args.outdir, 'compare_report.json')}")
    return 0 if status == "PASS" else 1


def parse_stream_expected(stream):
    return [(0, line.split()) for line in stream if line]


def run_mutant(args, name, program_path, expected_rows, meta, stats):
    define, description = MUTANTS[name]
    workdir = tempfile.mkdtemp(prefix="h05_mut_")
    try:
        actual_path, sim_meta = run_sim(args.iverilog, args.vvp, name,
                                        program_path, workdir)
        actual_rows = parse_stream(actual_path)
    finally:
        shutil.rmtree(workdir, ignore_errors=True)
    count, first, per_run = compare_streams(expected_rows, actual_rows,
                                            meta)
    failed = [i for i, r in enumerate(per_run) if r["status"] == "FAIL"]
    failed_algs = sorted({meta[i]["algorithm"] for i in failed})
    failed_fb_pos = [meta[i] for i in failed]
    if name == "oporder":
        met = len(failed_algs) >= 28
        detail = {"failed_algorithms": failed_algs,
                  "failed_algorithm_count": len(failed_algs)}
    else:
        # every feedback>0 run with a live feedback path must fail;
        # runs whose fb op is gate-skipped (fb_inert) carry no feedback
        # term, and feedback-0 runs never read the history -- those
        # legitimately survive a feedback-only defect.
        fb_pos_runs = [i for i, m in enumerate(meta)
                       if m["feedback"] > 0 and not m["fb_inert"]]
        missing = [i for i in fb_pos_runs if i not in set(failed)]
        met = not missing
        detail = {"failed_runs": len(failed),
                  "feedback_positive_runs": len(fb_pos_runs),
                  "surviving_feedback_positive_runs": missing[:8]}
    res = {
        "define": define,
        "description": description,
        "mismatch_records": count,
        "first_mismatch": first,
        **detail,
        "status": ("MET (mutant fails conformance as required)" if met
                   else "NOT MET (mutant passed -- harness has no "
                        "resolution)"),
        "met": met,
    }
    return res


if __name__ == "__main__":
    sys.exit(main())
